function showToast(m){const t=document.getElementById('toast');t.textContent=m;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2400)}function previewImage(e){const f=e.target.files?.[0],img=document.getElementById('image-preview');if(!f)return;img.src=URL.createObjectURL(f);img.style.display='block';document.getElementById('dropzone').style.display='none';showToast('Slika je učitana.')}function demoOcr(){document.getElementById('ocr-output').value='Danas radim na svom novom digitalnom proizvodu.\n\nOvo je [NEJASNO] mesto u rukopisu.\n\n🟡 AI pretpostavka: „novom“ — pouzdanost 82%.';showToast('Prepoznavanje je završeno. Proveri označene delove.')}function generateCopy(){const type=document.getElementById('copy-type').value,topic=document.getElementById('copy-topic').value.trim();if(!topic){showToast('Prvo napiši temu ili proizvod.');return}document.getElementById('copy-output').value=''+type+'\n\nTema: '+topic+'\n\nU ovom tekstu možemo jasno predstaviti problem, konkretnu vrednost i sledeći korak za čitaoca. Sadržaj će biti prilagođen izabranom formatu i tonu.\n\nCTA: Saznaj više i izaberi sledeći korak koji ti odgovara.';showToast('Nacrt je napravljen.')}function previewMockup(e){const f=e.target.files?.[0];if(!f)return;const stage=document.getElementById('mockup-stage');stage.innerHTML='';const type=document.getElementById('mockup-type')?.value||'';const img=document.createElement('img');img.className='mockup-image';img.src=URL.createObjectURL(f);img.alt='Pregled proizvoda';if(type==='Telefon ekran'){const frame=document.createElement('div');frame.className='mockup-screen-frame';frame.appendChild(img);stage.appendChild(frame);}else{stage.appendChild(img)}applyMockupFit();showToast('Slika je učitana bez razvlačenja.');}
function applyMockupFit(){const frame=document.querySelector('.mockup-screen-frame');const img=document.querySelector('.mockup-screen-frame .mockup-image');if(!frame||!img)return;const fit=document.getElementById('mockup-fit')?.value||'contain';const align=document.getElementById('mockup-align')?.value||'center';frame.classList.remove('fit-cover','fit-original','align-top','align-bottom');if(fit==='cover')frame.classList.add('fit-cover');if(fit==='original')frame.classList.add('fit-original');if(align==='top')frame.classList.add('align-top');if(align==='bottom')frame.classList.add('align-bottom');}
document.getElementById('mockup-type')?.addEventListener('change',()=>{const file=document.getElementById('mockup-input')?.files?.[0];if(file)renderMockupScene();});
function createMockup(){const file=document.getElementById('mockup-input')?.files?.[0];const type=document.getElementById('mockup-type')?.value||'proizvod';const prompt=document.getElementById('mockup-prompt')?.value.trim();if(!file){showToast('Prvo dodaj sliku proizvoda.');return}if(!prompt){showToast('Prompt je obavezan — opiši željenu scenu.');document.getElementById('mockup-prompt')?.focus();return}renderMockupScene();showToast(type+' mockup je pripremljen prema promptu.');}
document.querySelectorAll('.nav-item').forEach(i=>i.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));i.classList.add('active')}));
function buildProduct(){const v=document.getElementById('product-idea')?.value.trim(),type=document.getElementById('product-type')?.value||'Digitalni proizvod',aud=document.getElementById('product-audience')?.value.trim()||'idealni korisnik',goal=document.getElementById('product-goal')?.value||'Prodaja',offer=document.getElementById('product-offer')?.value.trim()||'jasna korist proizvoda';if(!v){showToast('Unesi ideju proizvoda.');return}
const set=(id,text)=>{const el=document.getElementById(id);if(el)el.value=text};
set('product-output',`PROIZVODNI PLAN\n\nNaziv / ideja: ${v}\nTip: ${type}\nPublika: ${aud}\nCilj: ${goal}\nPonuda: ${offer}\n\n1. Obećanje proizvoda\n2. Ishod za korisnika\n3. Struktura poglavlja / modula\n4. Vežbe, alati i radni listovi\n5. Bonus sadržaj\n6. Naslovna strana i vizuelni pravac\n7. Završni CTA\n\nSTATUS: spremno za razradu sadržaja.`);
set('sales-output',`PRODAJNA STRANICA\n\nHOOK\n${v} za ${aud}.\n\nPROBLEM\nKoji konkretan problem rešavaš i zašto korisnik želi promenu.\n\nREŠENJE\n${v} je ${type} koji vodi korisnika od početnog stanja do jasnog sledećeg koraka.\n\nŠTA DOBIJAŠ\n• Glavni rezultat\n• Praktični alati\n• Jednostavna primena\n• Bonus / dodatna vrednost\n\nPONUDA\n${offer}\n\nCTA: Pogledaj proizvod i napravi sledeći korak.`);
set('seo-output',`SEO PAKET\n\nPrimarna ključna tema: ${v}\nSekundarne teme: ${type}, ${aud}, vodič, šablon, alat, digitalni proizvod\n\nSEO naslov: ${v} — praktičan ${type} za ${aud}\nMeta opis: Otkrij ${v} i koristi praktičan sistem za ${aud}. Jasna struktura, alati i sledeći koraci na jednom mestu.\n\nSadržajni klaster:\n1. Problem koji proizvod rešava\n2. Kako se koristi\n3. Najčešća pitanja\n4. Besplatan sadržaj povezan sa proizvodom\n5. Prodajna stranica`);
set('pin-output',`PINTEREST PAKET\n\nPin 1 — Problem: ${v}: praktično rešenje za ${aud}\nPin 2 — Benefit: Kako da dobiješ rezultat uz ${v}\nPin 3 — Checklist: Šta dobijaš u ${type}\nPin 4 — CTA: Sačuvaj ovaj vodič i pogledaj ${v}\n\nBoard ideja: ${type} • ${aud}\nCTA: Saznaj više`);
set('social-output',`DRUŠTVENE MREŽE\n\nInstagram/Reels: Problem → kratko objašnjenje → ${v} → CTA\nLinkedIn: edukativni ugao + iskustvo + praktičan alat\nTikTok/Threads: jedna jaka ideja + pitanje publici\nStory: anketa → problem → rešenje → link\n\nGlavna poruka: ${v} pomaže ${aud} da naprave konkretan sledeći korak.`);
set('email-output',`EMAIL MINI SEKVENCA\n\nEmail 1 — Problem: uvedi temu i pokaži zašto je važna.\nEmail 2 — Vrednost: daj jedan konkretan savet iz ${v}.\nEmail 3 — Ponuda: predstavi ${v}, ${type} i glavnu korist.\nEmail 4 — Follow-up: odgovori na najčešću prepreku i pozovi na akciju.\n\nCTA: Pogledaj ${v}`);
set('drive-output',`MARIJANA DRIVE — PREDLOG STRUKTURE\n\n/Proizvodi/${v}/\n├── 01_Proizvod\n├── 02_Prodajna_stranica\n├── 03_SEO\n├── 04_Pinterest\n├── 05_Drustvene_mreze\n├── 06_Email\n├── 07_Mockup\n├── 08_Brand_assets\n└── 09_Analitika\n\nStatus: spremno za čuvanje i dalju automatizaciju.`);
showToast('ONE PRODUCT → EVERYTHING paket je pripremljen.');}
function saveProductSystem(){const data={name:document.getElementById('product-idea')?.value||'Novi proizvod',createdAt:new Date().toISOString(),product:document.getElementById('product-output')?.value||'',sales:document.getElementById('sales-output')?.value||'',seo:document.getElementById('seo-output')?.value||'',pinterest:document.getElementById('pin-output')?.value||'',social:document.getElementById('social-output')?.value||'',email:document.getElementById('email-output')?.value||'',drive:document.getElementById('drive-output')?.value||''};localStorage.setItem('marijanaProductSystem',JSON.stringify(data));showToast('Product System je sačuvan u ovom workspace-u.');}
document.addEventListener('click',e=>{const tab=e.target.closest('.result-tab');if(!tab)return;document.querySelectorAll('.result-tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.result-output').forEach(x=>x.classList.remove('active'));tab.classList.add('active');document.getElementById(tab.dataset.result)?.classList.add('active');});
function prepareMusic(){const p=document.getElementById('music-prompt').value.trim();const type=document.getElementById('music-type').value;const use=document.getElementById('music-use').value;if(!p){showToast('Opiši kakvu muziku želiš.');return}document.getElementById('music-output').value='MUZIČKI BRIEF\n\nOpis: '+p+'\n\nVrsta: '+type+'\nNamena: '+use+'\n\nAtmosfera: smirena, topla i dostojanstvena\nTempo: umeren / spor\nInstrumentacija: odabrati prema kulturnom i umetničkom kontekstu\nStruktura: uvod → glavna tema → razvoj → miran završetak\n\nNapomena: za stvarnu produkciju proveriti prava/licence za korišćene uzorke, snimke i muzičke materijale.';showToast('Muzički koncept je pripremljen.');}
function saveProject(){const data={savedAt:new Date().toISOString(),ocr:document.getElementById('ocr-output')?.value||'',copy:document.getElementById('copy-output')?.value||'',document:document.querySelector('.document-editor')?.innerHTML||'',product:document.getElementById('product-output')?.value||'',music:document.getElementById('music-output')?.value||''};localStorage.setItem('marijanaStudioProject',JSON.stringify(data));showToast('Projekat je sačuvan u ovom radnom prostoru.');}
function loadProject(){try{const d=JSON.parse(localStorage.getItem('marijanaStudioProject')||'null');if(!d)return;if(document.getElementById('ocr-output'))document.getElementById('ocr-output').value=d.ocr||'';if(document.getElementById('copy-output'))document.getElementById('copy-output').value=d.copy||'';if(document.querySelector('.document-editor')&&d.document)document.querySelector('.document-editor').innerHTML=d.document;if(document.getElementById('product-output'))document.getElementById('product-output').value=d.product||'';if(document.getElementById('music-output'))document.getElementById('music-output').value=d.music||'';}catch(e){}}
function newProject(){if(confirm('Otvoriti novi prazan projekat? Nesacuvan sadržaj u trenutnom projektu biće zamenjen.')){localStorage.removeItem('marijanaStudioProject');location.reload();}}
function exportDocument(kind){const editor=document.querySelector('.document-editor');const text=editor?.innerText||'';if(!text.trim()){showToast('Dokument je prazan.');return}const blob=new Blob([text],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Marijana-Dokument.txt';a.click();URL.revokeObjectURL(a.href);showToast(kind==='pdf'?'Sadržaj je izvezen kao tekstualni dokument; PDF modul će zadržati formatiranje.':'TXT je sačuvan.');}
function prepareImageBrief(){const area=[...document.querySelectorAll('#slika textarea,#slika input')].map(x=>x.value).filter(Boolean).join('\n');showToast('Vizuelni brief je spreman za povezivanje sa generatorom slike.');}
function prepareVideoBrief(){showToast('Video brief je spreman za povezivanje sa generatorom videa.');}
window.addEventListener('DOMContentLoaded',loadProject);

function setMockupPreset(preset){const prompt=document.getElementById('mockup-prompt'),type=document.getElementById('mockup-type');const presets={editorial:{type:'Magazine Editorial',text:'Premium editorial mockup, clean studio background, realistic paper depth, subtle soft shadows, elegant composition, luxury digital product presentation.'},paper:{type:'Paper Stack / Layered',text:'Layered paper sheets, multiple pages with slight offsets, realistic paper thickness, soft directional shadow, clean premium background.'},book:{type:'Otvorena knjiga',text:'Open book mockup, realistic center fold, gently curved pages, visible left and right spreads, natural paper shadows, editorial photography.'},isometric:{type:'Isometric Pages',text:'Isometric digital product scene, multiple pages at different angles, controlled perspective, realistic depth and shadows, premium presentation.'},'device-set':{type:'Desktop + Laptop + Tablet + Telefon',text:'Responsive device ecosystem showing the same product across desktop, laptop, tablet and phone, coordinated perspective, clean premium scene.'},frame:{type:'Frame / Okvir',text:'Elegant framed digital artwork or printable page, realistic frame depth, wall or gallery presentation, soft natural shadow, premium minimal interior.'}}[preset];if(!presets)return;if(type)type.value=presets.type;if(prompt)prompt.value=presets.text;const file=document.getElementById('mockup-input')?.files?.[0];if(file)previewMockup({target:{files:[file]}});showToast('Preset '+preset+' je izabran.');}

function updateMockupPages(){const v=document.getElementById('mockup-pages')?.value||3;const out=document.getElementById('mockup-pages-value');if(out)out.textContent=v;renderMockupScene();}
function renderMockupScene(){const stage=document.getElementById('mockup-stage'),file=document.getElementById('mockup-input')?.files?.[0],type=document.getElementById('mockup-type')?.value||'';if(!stage||!file)return;const src=window.__mockupObjectUrl||URL.createObjectURL(file);window.__mockupObjectUrl=src;const n=Math.min(6,Math.max(1,Number(document.getElementById('mockup-pages')?.value||3)));const perspective=document.getElementById('mockup-perspective')?.value||'soft';const shadow=document.getElementById('mockup-shadow')?.value||'soft';
const img=s=>'<img src="'+s+'" alt="Proizvodni vizual">';
const paperTypes=['Jedan list','Lebdeći list','Dva lista','Više listova / Stack','Floating Sheets','Paper Stack / Layered','Isometric Pages','Isometric Wall','Zig-Zag Pages','3D Paper Scene','Multi-Page Presentation','Page Turn / Savijeni list'];
if(type==='Otvorena knjiga'||type==='Otvorena radna sveska'||type==='Magazine Spread'||type==='Magazine Editorial'||type==='Blank Book / Brochure'){stage.innerHTML='<div class="open-book"><div class="book-page left">'+img(src)+'</div><div class="book-gutter"></div><div class="book-page right">'+img(src)+'</div></div>';return}
if(type==='Frame / Okvir'||type==='Gallery Frames'){stage.innerHTML='<div class="frame-scene"><div class="frame-object">'+img(src)+'</div></div>';return}
if(paperTypes.includes(type)){const scene=document.createElement('div');scene.className='paper-scene '+perspective+' shadow-'+shadow+(type==='Page Turn / Savijeni list'?' page-turn':'');for(let i=0;i<n;i++){const sheet=document.createElement('div');sheet.className='paper-sheet';sheet.style.setProperty('--sheet-index',i);sheet.appendChild(Object.assign(document.createElement('img'),{src,alt:'Stranica proizvoda'}));scene.appendChild(sheet)}stage.innerHTML='';stage.appendChild(scene);apply3DTransform(scene);return}
if(type==='Desktop + Laptop + Tablet + Telefon'){stage.innerHTML='<div class="device-ecosystem"><div class="device desktop">'+img(src)+'</div><div class="device laptop">'+img(src)+'</div><div class="device tablet">'+img(src)+'</div><div class="device phone">'+img(src)+'</div></div>';return}
if(type==='Laptop ekran'||type==='Tablet ekran'||type==='Telefon ekran'){stage.innerHTML='';const wrap=document.createElement('div');wrap.className='single-device '+(type==='Laptop ekran'?'device-laptop':type==='Tablet ekran'?'device-tablet':'device-phone');wrap.innerHTML=img(src);stage.appendChild(wrap);apply3DTransform(wrap);return}
if(type==='Bundle proizvoda'||type==='Product Ecosystem'||type==='3D proizvod'){const scene=document.createElement('div');scene.className='product-ecosystem';for(let i=0;i<n;i++){const card=document.createElement('div');card.className='eco-card';card.style.setProperty('--i',i);card.innerHTML=img(src);scene.appendChild(card)}stage.innerHTML='';stage.appendChild(scene);apply3DTransform(scene);return}
if(type==='Desk Scene'||type==='Lifestyle Scene'||type==='Photo / Collage'){stage.innerHTML='<div class="lifestyle-scene"><div class="scene-backdrop"></div><div class="scene-product">'+img(src)+'</div><div class="scene-shadow"></div></div>';return}
previewMockup({target:{files:[file]}});}

function updateTransformValue(kind){const ids={['rotate-x']:'rotate-x-value',['rotate-y']:'rotate-y-value',['rotate-z']:'rotate-z-value',depth:'depth-value',scale:'scale-value'};const input=document.getElementById('mockup-'+kind),out=document.getElementById(ids[kind]);if(input&&out)out.textContent=input.value+(kind.startsWith('rotate')?'°':kind==='scale'?'%':'');renderMockupScene();}
function apply3DTransform(el){if(!el)return;const mode=document.getElementById('mockup-mode')?.value||'3d';const rx=document.getElementById('mockup-rotate-x')?.value||0,ry=document.getElementById('mockup-rotate-y')?.value||0,rz=document.getElementById('mockup-rotate-z')?.value||0,depth=document.getElementById('mockup-depth')?.value||0,scale=(document.getElementById('mockup-scale')?.value||100)/100;if(mode==='2d'){el.style.transform='translateZ('+depth+'px) rotateZ('+rz+'deg) scale('+scale+')';}else{el.style.transform='translateZ('+depth+'px) rotateX('+rx+'deg) rotateY('+ry+'deg) rotateZ('+rz+'deg) scale('+scale+')';}}

function selectPlan(plan){localStorage.setItem('marijanaSelectedPlan',plan);showToast(plan==='Free'?'Free plan je izabran.':plan+' plan je izabran — naplata će biti povezana kada postavimo billing.');}
