function showToast(m){const t=document.getElementById('toast');t.textContent=m;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2400)}function previewImage(e){const f=e.target.files?.[0],img=document.getElementById('image-preview');if(!f)return;img.src=URL.createObjectURL(f);img.style.display='block';document.getElementById('dropzone').style.display='none';showToast('Slika je učitana.')}function demoOcr(){document.getElementById('ocr-output').value='Danas radim na svom novom digitalnom proizvodu.\n\nOvo je [NEJASNO] mesto u rukopisu.\n\n🟡 AI pretpostavka: „novom“ — pouzdanost 82%.';showToast('Prepoznavanje je završeno. Proveri označene delove.')}function generateCopy(){const type=document.getElementById('copy-type').value,topic=document.getElementById('copy-topic').value.trim();if(!topic){showToast('Prvo napiši temu ili proizvod.');return}document.getElementById('copy-output').value=''+type+'\n\nTema: '+topic+'\n\nU ovom tekstu možemo jasno predstaviti problem, konkretnu vrednost i sledeći korak za čitaoca. Sadržaj će biti prilagođen izabranom formatu i tonu.\n\nCTA: Saznaj više i izaberi sledeći korak koji ti odgovara.';showToast('Nacrt je napravljen.')}function previewMockup(e){const f=e.target.files?.[0];if(!f)return;const stage=document.getElementById('mockup-stage');stage.innerHTML='';const img=document.createElement('img');img.className='mockup-image';img.src=URL.createObjectURL(f);img.alt='Pregled proizvoda';stage.appendChild(img);showToast('Naslovna slika proizvoda je učitana.');}
function createMockup(){const file=document.getElementById('mockup-input')?.files?.[0];const type=document.getElementById('mockup-type')?.value||'proizvod';if(!file){showToast('Prvo dodaj sliku proizvoda.');return}showToast(type+' mockup je pripremljen za AI generisanje.');}
document.querySelectorAll('.nav-item').forEach(i=>i.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));i.classList.add('active')}));
function buildProduct(){const v=document.getElementById('product-idea').value.trim();if(!v){showToast('Unesi ideju proizvoda.');return}document.getElementById('product-output').value='STRUKTURA PROIZVODA\n\n'+v+'\n\n1. Cilj proizvoda\n2. Idealni korisnik\n3. Struktura i poglavlja\n4. Vežbe / alati / radni listovi\n5. Naslovna strana i vizuelni stil\n6. Prodajni opis i CTA\n7. Mockup\n8. SEO i Pinterest sadržaj\n9. Newsletter i launch sadržaj\n10. Organizacija u Marijana Drive';showToast('Osnovna struktura proizvoda je napravljena.');}
function prepareMusic(){const p=document.getElementById('music-prompt').value.trim();const type=document.getElementById('music-type').value;const use=document.getElementById('music-use').value;if(!p){showToast('Opiši kakvu muziku želiš.');return}document.getElementById('music-output').value='MUZIČKI BRIEF\n\nOpis: '+p+'\n\nVrsta: '+type+'\nNamena: '+use+'\n\nAtmosfera: smirena, topla i dostojanstvena\nTempo: umeren / spor\nInstrumentacija: odabrati prema kulturnom i umetničkom kontekstu\nStruktura: uvod → glavna tema → razvoj → miran završetak\n\nNapomena: za stvarnu produkciju proveriti prava/licence za korišćene uzorke, snimke i muzičke materijale.';showToast('Muzički koncept je pripremljen.');}
function saveProject(){const data={savedAt:new Date().toISOString(),ocr:document.getElementById('ocr-output')?.value||'',copy:document.getElementById('copy-output')?.value||'',document:document.querySelector('.document-editor')?.innerHTML||'',product:document.getElementById('product-output')?.value||'',music:document.getElementById('music-output')?.value||''};localStorage.setItem('marijanaStudioProject',JSON.stringify(data));showToast('Projekat je sačuvan u ovom radnom prostoru.');}
function loadProject(){try{const d=JSON.parse(localStorage.getItem('marijanaStudioProject')||'null');if(!d)return;if(document.getElementById('ocr-output'))document.getElementById('ocr-output').value=d.ocr||'';if(document.getElementById('copy-output'))document.getElementById('copy-output').value=d.copy||'';if(document.querySelector('.document-editor')&&d.document)document.querySelector('.document-editor').innerHTML=d.document;if(document.getElementById('product-output'))document.getElementById('product-output').value=d.product||'';if(document.getElementById('music-output'))document.getElementById('music-output').value=d.music||'';}catch(e){}}
function newProject(){if(confirm('Otvoriti novi prazan projekat? Nesacuvan sadržaj u trenutnom projektu biće zamenjen.')){localStorage.removeItem('marijanaStudioProject');location.reload();}}
function exportDocument(kind){const editor=document.querySelector('.document-editor');const text=editor?.innerText||'';if(!text.trim()){showToast('Dokument je prazan.');return}const blob=new Blob([text],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='Marijana-Dokument.txt';a.click();URL.revokeObjectURL(a.href);showToast(kind==='pdf'?'Sadržaj je izvezen kao tekstualni dokument; PDF modul će zadržati formatiranje.':'TXT je sačuvan.');}
function prepareImageBrief(){const area=[...document.querySelectorAll('#slika textarea,#slika input')].map(x=>x.value).filter(Boolean).join('\n');showToast('Vizuelni brief je spreman za povezivanje sa generatorom slike.');}
function prepareVideoBrief(){showToast('Video brief je spreman za povezivanje sa generatorom videa.');}
window.addEventListener('DOMContentLoaded',loadProject);
