const fallbackModules=[{id:"drive",name:"Marijana Drive",desc:"Centralni workspace, fajlovi, projekti i poslovni sistem.",status:"ready",deps:[]},{id:"creator",name:"Marijana Creator",desc:"Kreiranje dokumenata, stranica, vizuala i eksport.",status:"ready",deps:["drive"]},{id:"ai",name:"Marijana AI Studio",desc:"AI alati i centralni AI sloj.",status:"ready",deps:[]},{id:"contacts",name:"Marijana Kontakti",desc:"Kontakti, odnosi i relationship intelligence.",status:"ready",deps:["drive"]},{id:"automation",name:"Marijana Automatizacije",desc:"Workflow i automatizacija poslovnih procesa.",status:"ready",deps:["drive"]},{id:"calendar",name:"Marijana Kalendar",desc:"Planiranje sadržaja, događaja i zadataka.",status:"ready",deps:["drive"]},{id:"audio",name:"Marijana Audio Studio",desc:"Voice, audio production, mastering i export.",status:"planned",deps:["ai"]},{id:"agents",name:"Marijana Agent OS",desc:"AI agenti, orkestracija i kontrolisana autonomija.",status:"planned",deps:["ai","automation"]},{id:"billing",name:"Marijana Naplata",desc:"Billing, subscriptions, entitlements i finansijske operacije.",status:"planned",deps:["drive"]},{id:"analytics",name:"Marijana Analitika",desc:"Metrike, događaji i poslovna analitika.",status:"planned",deps:["drive"]}];
const fallbackChecks=[{id:"database",name:"Database",desc:"Baza podataka i migracioni sloj",state:"pending"},{id:"api",name:"API",desc:"Centralni API i autentifikacija",state:"pending"},{id:"storage",name:"Storage",desc:"Fajlovi i media storage",state:"pending"},{id:"auth",name:"Authentication",desc:"Identitet i pristup",state:"pending"},{id:"ai",name:"AI Core",desc:"AI konfiguracija i runtime",state:"pending"},{id:"scheduler",name:"Scheduler",desc:"Zakazivanje i background jobs",state:"pending"},{id:"deploy",name:"Deployment",desc:"Build i release pipeline",state:"pending"}];
let modules=[...fallbackModules],checks=[...fallbackChecks];let migrationData=[];let audit=[];
function log(msg){audit.unshift({time:new Date().toLocaleTimeString("sr-RS"),msg});renderAudit()}
function statusLabel(s){return s==="ready"?"SPREMNO":s==="planned"?"PLANIRANO":s==="pending"?"PROVERA":"GREŠKA"}
function renderHealth(){document.querySelector("#health-grid").innerHTML=checks.map(c=>`<div class="health-card"><span class="eyebrow">${c.name}</span><h3>${c.state==="ready"?"🟢":c.state==="error"?"🔴":"🟡"} ${statusLabel(c.state)}</h3><div class="state">${c.desc||c.detail||""}</div></div>`).join("");document.querySelector("#health-detail").innerHTML=checks.map(c=>`<div class="health-card"><span class="eyebrow">${c.name}</span><h3>${c.state==="ready"?"Operativno":c.state==="error"?"Greška":"Potrebna provera"}</h3><p>${c.desc||c.detail||""}</p><span class="${c.state==="ready"?"ok":c.state==="error"?"bad":"warn"}">${c.state==="ready"?"✓ Check passed":c.state==="error"?"✕ Check failed":"! Check required"}</span></div>`).join("")}
function renderModules(){document.querySelector("#module-grid").innerHTML=modules.map(m=>`<div class="module-card"><span class="eyebrow">MODULE</span><h3>${m.name}</h3><p>${m.desc||"Modul"}</p><div class="module-meta"><span class="badge">${statusLabel(m.status)}</span><button class="secondary" onclick="moduleAction('${m.id}')">${m.status==="ready"?"Otvori":"Konfiguriši"}</button></div></div>`).join("")}
function renderMigrations(){const list=migrationData.length?migrationData:[];document.querySelector("#migration-list").innerHTML=list.length?list.map(m=>`<div class="list-row"><span><strong>${m.id} · ${m.name}</strong></span><span class="${m.status==="applied"?"ok":"warn"}">${m.status==="applied"?"✓ PRIMENJENO":m.status==="pending"?"! PENDING":"PLANIRANO"}</span></div>`).join(""):'<div class="result">Migracije se učitavaju…</div>'}
function renderAudit(){document.querySelector("#audit-list").innerHTML=audit.length?audit.map(a=>`<div class="list-row"><span>${a.msg}</span><small>${a.time}</small></div>`).join(""):'<div class="result">Još nema operacija.</div>'}
async function recordAudit(action,details={}){log(action);try{await fetch("../api/system/audit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,details})})}catch(e){}}
async function runFullCheck(){document.querySelector("#launch-result").textContent="Proveravam stvarni backend…";try{const r=await fetch("../api/system/health");const data=await r.json();if(!r.ok)throw new Error(data.error||"Health API error");checks=data.checks||fallbackChecks;renderHealth();document.querySelector("#launch-result").innerHTML='<span class="ok">✓ System Check završen.</span> Backend je odgovorio. Stavke PENDING zahtevaju konfiguraciju.';recordAudit("FULL_SYSTEM_CHECK",{checks});}catch(e){checks=fallbackChecks;renderHealth();document.querySelector("#launch-result").innerHTML='<span class="warn">! Backend health API nije dostupan.</span> Launcher radi u sigurnom fallback režimu.';recordAudit("HEALTH_FALLBACK",{message:e.message})}}
async function loadModules(){try{const r=await fetch("../api/system/modules");const data=await r.json();if(r.ok&&data.modules){modules=data.modules;renderModules();recordAudit("MODULE_REGISTRY_LOADED")}}catch(e){log("Module API nije dostupan — lokalni registry")}}
async function loadAudit(){try{const r=await fetch("../api/system/audit");const data=await r.json();if(r.ok&&data.events){audit=data.events.map(x=>({time:new Date(x.created_at).toLocaleTimeString("sr-RS"),msg:x.action}));renderAudit()}}catch(e){}}
async function loadMigrations(){try{const r=await fetch("../api/system/migrations");const data=await r.json();if(r.ok){migrationData=data.migrations||[];renderMigrations();}}catch(e){renderMigrations()}}
async function createDeploymentPlan(){const target=document.querySelector("#deploy-target").value;const box=document.querySelector("#deploy-plan");box.innerHTML='<div class="result">Kreiram deployment plan…</div>';try{const r=await fetch("../api/system/deployment-plan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({target})});const data=await r.json();if(!r.ok)throw new Error(data.error||"Plan error");box.innerHTML=data.steps.map(s=>`<div class="list-row"><span>${s.name}</span><span class="warn">CHECK</span></div>`).join("");recordAudit("DEPLOYMENT_PLAN_CREATED",{target,plan_id:data.plan_id})}catch(e){box.innerHTML='<div class="result"><span class="bad">Plan nije kreiran.</span> Proveri backend.</div>';recordAudit("DEPLOYMENT_PLAN_FAILED",{message:e.message})}}
async function dependencyCheck(){try{const r=await fetch("../api/system/dependencies");const d=await r.json();recordAudit("DEPENDENCY_CHECK",{ok:d.ok,missing:d.missing});return d}catch(e){return{ok:false,missing:[{module:"system",dependency:"dependency-api"}]}}}
async function smokeTests(){try{const r=await fetch("../api/system/smoke-tests");const d=await r.json();recordAudit("SMOKE_TEST_REGISTRY",{count:d.tests?.length||0});return d}catch(e){return{tests:[]}}}
async function prepareDeployment(){const blocking=checks.filter(c=>c.state!=="ready");const deps=await dependencyCheck();const smoke=await smokeTests();const migrationPending=migrationData.filter(m=>m.status!=="applied").length;const blockers=blocking.length+(deps.missing?.length||0)+(migrationPending?1:0);document.querySelector("#launch-result").innerHTML=blockers?'<span class="warn">DEPLOYMENT BLOKIRAN</span><br>'+blockers+' uslova još nije READY. Produkcija ostaje zaključana.':'<span class="ok">✓ DEPLOYMENT READY</span><br>Health, dependencies, migrations i smoke-test registry su spremni. Produkcija i dalje zahteva eksplicitnu potvrdu.';recordAudit("DEPLOYMENT_READINESS_CHECK",{blockers,migrationPending,smoke_tests:smoke.tests?.length||0})}
function moduleAction(id){const m=modules.find(x=>x.id===id);if(!m)return;recordAudit(m.status==="ready"?"MODULE_OPENED":"MODULE_CONFIGURATION_STARTED",{module_id:id});alert(m.status==="ready"?m.name+" je registrovan kao READY modul.":"Modul "+m.name+" je u fazi "+statusLabel(m.status)+".")}
document.querySelectorAll(".nav").forEach(n=>n.onclick=()=>{document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));n.classList.add("active");document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));document.querySelector("#view-"+n.dataset.view).classList.add("active");document.querySelector("#view-title").textContent=n.textContent.replace(/^[^\s]+\s/,"")});
renderHealth();renderModules();renderMigrations();renderAudit();loadModules();loadAudit();loadMigrations();