const fallbackModules=[{id:"drive",name:"Marijana Drive",desc:"Centralni workspace, fajlovi, projekti i poslovni sistem.",status:"ready",deps:[]},{id:"creator",name:"Marijana Creator",desc:"Kreiranje dokumenata, stranica, vizuala i eksport.",status:"ready",deps:["drive"]},{id:"ai",name:"Marijana AI Studio",desc:"AI alati i centralni AI sloj.",status:"ready",deps:[]},{id:"contacts",name:"Marijana Kontakti",desc:"Kontakti i relationship intelligence.",status:"ready",deps:["drive"]},{id:"automation",name:"Marijana Automatizacije",desc:"Workflow i automatizacija.",status:"ready",deps:["drive"]},{id:"calendar",name:"Marijana Kalendar",desc:"Planiranje sadržaja i događaja.",status:"ready",deps:["drive"]},{id:"audio",name:"Marijana Audio Studio",desc:"Voice, audio production i mastering.",status:"planned",deps:["ai"]},{id:"agents",name:"Marijana Agent OS",desc:"AI agenti i orkestracija.",status:"planned",deps:["ai","automation"]},{id:"billing",name:"Marijana Naplata",desc:"Billing i subscriptions.",status:"planned",deps:["drive"]},{id:"analytics",name:"Marijana Analitika",desc:"Metrike i poslovna analitika.",status:"planned",deps:["drive"]}];
const fallbackChecks=[{id:"database",name:"Database",desc:"Baza podataka",state:"pending"},{id:"api",name:"API",desc:"Centralni API",state:"pending"},{id:"storage",name:"Storage",desc:"Storage",state:"pending"},{id:"auth",name:"Authentication",desc:"Identitet i pristup",state:"pending"},{id:"ai",name:"AI Core",desc:"AI runtime",state:"pending"},{id:"scheduler",name:"Scheduler",desc:"Background jobs",state:"pending"},{id:"deploy",name:"Deployment",desc:"Build i release",state:"pending"}];
let modules=fallbackModules.slice(),checks=fallbackChecks.slice(),migrationData=[],audit=[],moduleStates=[];
function statusLabel(s){return ({ready:"SPREMNO",planned:"PLANIRANO",pending:"PROVERA",active:"AKTIVNO",disabled:"ISKLJUČENO",installed:"INSTALIRANO",configured:"KONFIGURISANO",testing:"TESTIRANJE",upgrading:"UPGRADE",error:"GREŠKA"})[s]||s}
function log(msg){audit.unshift({time:new Date().toLocaleTimeString("sr-RS"),msg:msg});renderAudit()}
function renderAudit(){document.querySelector("#audit-list").innerHTML=audit.length?audit.map(function(a){return "<div class=\"list-row\"><span>"+a.msg+"</span><small>"+a.time+"</small></div>"}).join(""):"<div class=\"result\">Još nema operacija.</div>"}
function renderHealth(){document.querySelector("#health-grid").innerHTML=checks.map(function(c){return "<div class=\"health-card\"><span class=\"eyebrow\">"+c.name+"</span><h3>"+(c.state==="ready"?"🟢":c.state==="error"?"🔴":"🟡")+" "+statusLabel(c.state)+"</h3><div class=\"state\">"+(c.desc||c.detail||"")+"</div></div>"}).join("");document.querySelector("#health-detail").innerHTML=checks.map(function(c){return "<div class=\"health-card\"><span class=\"eyebrow\">"+c.name+"</span><h3>"+(c.state==="ready"?"Operativno":c.state==="error"?"Greška":"Potrebna provera")+"</h3><p>"+(c.desc||c.detail||"")+"</p></div>"}).join("")}
function stateFor(id){var s=moduleStates.find(function(x){return x.module_id===id});return s&&s.state==="active"?"disable":s&&s.state==="disabled"?"activate":"configure"}
function renderModules(){document.querySelector("#module-grid").innerHTML=modules.map(function(m){var s=moduleStates.find(function(x){return x.module_id===m.id});var state=s?s.state:(m.status==="ready"?"active":"planned");return "<div class=\"module-card\"><span class=\"eyebrow\">MODULE</span><h3>"+m.name+"</h3><p>"+m.desc+"</p><div class=\"module-meta\"><span class=\"badge\">"+statusLabel(state)+"</span><div class=\"module-actions\"><button class=\"secondary\" onclick=\"moduleLifecycle('"+m.id+"','install')\">Install</button><button class=\"secondary\" onclick=\"moduleLifecycle('"+m.id+"',stateFor('"+m.id+"'))\">"+(state==="active"?"Disable":state==="disabled"?"Activate":"Configure")+"</button><button class=\"secondary\" onclick=\"moduleLifecycle('"+m.id+"','upgrade')\">Upgrade</button></div></div></div>"}).join("")}
function renderMigrations(){document.querySelector("#migration-list").innerHTML=migrationData.length?migrationData.map(function(m){return "<div class=\"list-row\"><span><strong>"+m.id+" · "+m.name+"</strong></span><span>"+(m.status==="applied"?"✓ PRIMENJENO":m.status==="pending"?"! PENDING":"PLANIRANO")+"</span></div>"}).join(""):"<div class=\"result\">Migracije se učitavaju…</div>"}
function renderReleases(d){document.querySelector("#release-list").innerHTML="<div class=\"list-row\"><span><strong>Trenutna verzija</strong><br><small>"+d.current.version+" · "+d.current.channel+"</small></span><span class=\"ok\">✓ "+d.current.status+"</span></div><div class=\"list-row\"><span><strong>Sledeći release</strong><br><small>"+d.next.version+" · "+d.next.channel+"</small></span><span class=\"warn\">"+d.next.status+"</span></div>"}
function renderGraph(d){var box=document.querySelector("#dependency-graph");box.innerHTML=d.nodes.map(function(n){var out=d.edges.filter(function(e){return e[0]===n.id}).map(function(e){var x=d.nodes.find(function(z){return z.id===e[1]});return x&&x.label}).filter(Boolean);return "<div class=\"graph-card\"><span class=\"eyebrow\">"+n.layer+"</span><h3>"+n.label+"</h3><p><strong>Zavisi od:</strong> "+(out.length?out.join(", "):"Core / nema")+"</p></div>"}).join("")}
async function recordAudit(action,details){details=details||{};log(action);try{await fetch("../api/system/audit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:action,details:details})})}catch(e){}}
async function runFullCheck(){var box=document.querySelector("#launch-result");box.textContent="Proveravam stvarni backend…";try{var r=await fetch("../api/system/health"),d=await r.json();if(!r.ok)throw Error(d.error||"Health error");checks=d.checks||fallbackChecks;renderHealth();box.innerHTML="<span class=\"ok\">✓ System Check završen.</span> Backend je odgovorio.";recordAudit("FULL_SYSTEM_CHECK",{checks:checks})}catch(e){checks=fallbackChecks;renderHealth();box.innerHTML="<span class=\"warn\">! Backend health API nije dostupan.</span>";recordAudit("HEALTH_FALLBACK",{message:e.message})}}
async function loadModules(){try{var r=await fetch("../api/system/modules"),d=await r.json();if(r.ok&&d.modules){modules=d.modules;renderModules()}}catch(e){}}
async function loadModuleStates(){try{var r=await fetch("../api/system/module-state"),d=await r.json();if(r.ok){moduleStates=d.states||[];renderModules()}}catch(e){}}
async function moduleLifecycle(moduleId,action){try{var r=await fetch("../api/system/module-lifecycle",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({module_id:moduleId,action:action})}),d=await r.json();if(!r.ok)throw Error(d.error||"Lifecycle error");recordAudit("MODULE_LIFECYCLE",{module_id:moduleId,action:action,state:d.state});loadModuleStates()}catch(e){recordAudit("MODULE_LIFECYCLE_FAILED",{module_id:moduleId,action:action,message:e.message})}}
async function loadGraph(){try{var r=await fetch("../api/system/dependency-graph"),d=await r.json();if(r.ok)renderGraph(d)}catch(e){}}
async function loadAudit(){try{var r=await fetch("../api/system/audit"),d=await r.json();if(r.ok&&d.events){audit=d.events.map(function(x){return {time:new Date(x.created_at).toLocaleTimeString("sr-RS"),msg:x.action}});renderAudit()}}catch(e){}}
async function loadMigrations(){try{var r=await fetch("../api/system/migrations"),d=await r.json();if(r.ok){migrationData=d.migrations||[];renderMigrations()}}catch(e){renderMigrations()}}
async function loadReleases(){try{var r=await fetch("../api/system/releases"),d=await r.json();if(r.ok)renderReleases(d)}catch(e){}}
async function createDeploymentPlan(){var target=document.querySelector("#deploy-target").value,box=document.querySelector("#deploy-plan");box.innerHTML="<div class=\"result\">Kreiram deployment plan…</div>";try{var r=await fetch("../api/system/deployment-plan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({target:target})}),d=await r.json();if(!r.ok)throw Error(d.error||"Plan error");box.innerHTML=d.steps.map(function(s){return "<div class=\"list-row\"><span>"+s.name+"</span><span class=\"warn\">CHECK</span></div>"}).join("");recordAudit("DEPLOYMENT_PLAN_CREATED",{target:target,plan_id:d.plan_id})}catch(e){recordAudit("DEPLOYMENT_PLAN_FAILED",{message:e.message})}}
async function dependencyCheck(){try{var r=await fetch("../api/system/dependencies"),d=await r.json();recordAudit("DEPENDENCY_CHECK",{ok:d.ok,missing:d.missing});return d}catch(e){return {ok:false,missing:[{module:"system",dependency:"dependency-api"}]}}}
async function smokeTests(){try{var r=await fetch("../api/system/smoke-tests"),d=await r.json();return d}catch(e){return {tests:[]}}}
async function prepareDeployment(){var deps=await dependencyCheck(),smoke=await smokeTests(),pending=migrationData.filter(function(m){return m.status!=="applied"}).length,blockers=checks.filter(function(c){return c.state!=="ready"}).length+(deps.missing||[]).length+(pending?1:0);document.querySelector("#launch-result").innerHTML=blockers?"<span class=\"warn\">DEPLOYMENT BLOKIRAN</span><br>"+blockers+" uslova još nije READY.":"<span class=\"ok\">✓ DEPLOYMENT READY</span><br>Health, dependencies, migrations i smoke tests su spremni.";recordAudit("DEPLOYMENT_READINESS_CHECK",{blockers:blockers,smoke_tests:(smoke.tests||[]).length})}
async function planRollback(){var release=prompt("Koju verziju želiš da pripremimo za rollback?","0.1.0");if(!release)return;var r=await fetch("../api/system/rollback",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({release:release})});document.querySelector("#rollback-result").innerHTML=r.ok?"<span class=\"ok\">✓ Rollback plan pripremljen.</span>":"<span class=\"bad\">Rollback plan nije napravljen.</span>";recordAudit("ROLLBACK_PLAN_CREATED",{release:release,ok:r.ok})}
document.querySelectorAll(".nav").forEach(function(n){n.onclick=function(){document.querySelectorAll(".nav").forEach(function(x){x.classList.remove("active")});n.classList.add("active");document.querySelectorAll(".view").forEach(function(v){v.classList.remove("active")});document.querySelector("#view-"+n.dataset.view).classList.add("active");document.querySelector("#view-title").textContent=n.textContent.replace(/^[^\\s]+\\s/,"")}});
renderHealth();renderModules();renderMigrations();renderAudit();loadModules();loadModuleStates();loadGraph();loadAudit();loadMigrations();loadReleases();