const fallbackModules=[{id:"drive",name:"Marijana Drive",desc:"Centralni workspace, fajlovi, projekti i poslovni sistem.",status:"ready",deps:[]},{id:"creator",name:"Marijana Creator",desc:"Kreiranje dokumenata, stranica, vizuala i eksport.",status:"ready",deps:["drive"]},{id:"ai",name:"Marijana AI Studio",desc:"AI alati i centralni AI sloj.",status:"ready",deps:[]},{id:"contacts",name:"Marijana Kontakti",desc:"Kontakti i relationship intelligence.",status:"ready",deps:["drive"]},{id:"automation",name:"Marijana Automatizacije",desc:"Workflow i automatizacija.",status:"ready",deps:["drive"]},{id:"calendar",name:"Marijana Kalendar",desc:"Planiranje sadržaja i događaja.",status:"ready",deps:["drive"]},{id:"audio",name:"Marijana Audio Studio",desc:"Voice, audio production i mastering.",status:"planned",deps:["ai"]},{id:"agents",name:"Marijana Agent OS",desc:"AI agenti i orkestracija.",status:"planned",deps:["ai","automation"]},{id:"billing",name:"Marijana Naplata",desc:"Billing i subscriptions.",status:"planned",deps:["drive"]},{id:"analytics",name:"Marijana Analitika",desc:"Metrike i poslovna analitika.",status:"planned",deps:["drive"]}];
const fallbackChecks=[{id:"database",name:"Baza",desc:"Baza podataka",state:"pending"},{id:"api",name:"API",desc:"Centralni API",state:"pending"},{id:"storage",name:"Skladište",desc:"Skladište fajlova",state:"pending"},{id:"auth",name:"Pristup",desc:"Identitet i pristup",state:"pending"},{id:"ai",name:"AI jezgro",desc:"AI runtime",state:"pending"},{id:"scheduler",name:"Raspoređivač",desc:"Pozadinski poslovi",state:"pending"},{id:"deploy",name:"Deployment",desc:"Build i release",state:"pending"}];
let modules=fallbackModules.slice(),checks=fallbackChecks.slice(),migrationData=[],audit=[],moduleStates=[],executions=[],workers=[],queue=[],schedules=[],orchestrations=[];
function statusLabel(s){return ({ready:"SPREMNO",planned:"PLANIRANO",pending:"PROVERA",active:"AKTIVNO",disabled:"ISKLJUČENO",installed:"INSTALIRANO",configured:"KONFIGURISANO",testing:"TESTIRANJE",upgrading:"NADOGRADNJA",queued:"U REDU",running:"U TOKU",completed:"ZAVRŠENO",cancelled:"OTKAZANO",failed:"GREŠKA",idle:"MIROVANJE"}[s]||s)}
function log(msg){audit.unshift({time:new Date().toLocaleTimeString("sr-RS"),msg:msg});renderAudit()}
function renderAudit(){document.querySelector("#audit-list").innerHTML=audit.length?audit.map(function(a){return "<div class=\"list-row\"><span>"+a.msg+"</span><small>"+a.time+"</small></div>"}).join(""):"<div class=\"result\">Još nema operacija.</div>"}
function renderHealth(){document.querySelector("#health-grid").innerHTML=checks.map(function(c){return "<div class=\"health-card\"><span class=\"eyebrow\">"+c.name+"</span><h3>"+(c.state==="ready"?"🟢":c.state==="error"?"🔴":"🟡")+" "+statusLabel(c.state)+"</h3><div class=\"state\">"+(c.desc||c.detail||"")+"</div></div>"}).join("");document.querySelector("#health-detail").innerHTML=checks.map(function(c){return "<div class=\"health-card\"><span class=\"eyebrow\">"+c.name+"</span><h3>"+(c.state==="ready"?"Operativno":c.state==="error"?"Greška":"Potrebna provera")+"</h3><p>"+(c.desc||c.detail||"")+"</p></div>"}).join("")}
function stateFor(id){var s=moduleStates.find(function(x){return x.module_id===id});return s&&s.state==="active"?"disable":s&&s.state==="disabled"?"activate":"configure"}
function renderModules(){document.querySelector("#module-grid").innerHTML=modules.map(function(m){var s=moduleStates.find(function(x){return x.module_id===m.id});var state=s?s.state:(m.status==="ready"?"active":"planned");return "<div class=\"module-card\"><span class=\"eyebrow\">MODUL</span><h3>"+m.name+"</h3><p>"+m.desc+"</p><div class=\"module-meta\"><span class=\"badge\">"+statusLabel(state)+"</span><div class=\"module-actions\"><button class=\"secondary\" onclick=\"moduleLifecycle('"+m.id+"','install')\">Instaliraj</button><button class=\"secondary\" onclick=\"moduleLifecycle('"+m.id+"',stateFor('"+m.id+"'))\">"+(state==="active"?"Isključi":state==="disabled"?"Aktiviraj":"Konfiguriši")+"</button><button class=\"secondary\" onclick=\"moduleLifecycle('"+m.id+"','upgrade')\">Nadogradi</button></div></div></div>"}).join("")}
function renderMigrations(){document.querySelector("#migration-list").innerHTML=migrationData.length?migrationData.map(function(m){return "<div class=\"list-row\"><span><strong>"+m.id+" · "+m.name+"</strong></span><span>"+(m.status==="applied"?"✓ PRIMENJENO":m.status==="pending"?"! ČEKA":"PLANIRANO")+"</span></div>"}).join(""):"<div class=\"result\">Migracije se učitavaju…</div>"}
function renderReleases(d){document.querySelector("#release-list").innerHTML="<div class=\"list-row\"><span><strong>Trenutna verzija</strong><br><small>"+d.current.version+" · "+d.current.channel+"</small></span><span class=\"ok\">✓ "+d.current.status+"</span></div><div class=\"list-row\"><span><strong>Sledeća verzija</strong><br><small>"+d.next.version+" · "+d.next.channel+"</small></span><span class=\"warn\">"+d.next.status+"</span></div>"}
function renderGraph(d){document.querySelector("#dependency-graph").innerHTML=d.nodes.map(function(n){var out=d.edges.filter(function(e){return e[0]===n.id}).map(function(e){var x=d.nodes.find(function(z){return z.id===e[1]});return x&&x.label}).filter(Boolean);return "<div class=\"graph-card\"><span class=\"eyebrow\">"+n.layer+"</span><h3>"+n.label+"</h3><p><strong>Zavisi od:</strong> "+(out.length?out.join(", "):"Osnovni sloj / nema")+"</p></div>"}).join("")}
function renderExecutions(){var box=document.querySelector("#execution-list");if(!box)return;box.innerHTML=executions.length?executions.map(function(e){var actions=e.status==="queued"?"<button class=\"secondary\" onclick=\"executionAction('"+e.id+"','start')\">Pokreni</button>":e.status==="running"?"<button class=\"secondary\" onclick=\"executionAction('"+e.id+"','cancel')\">Zaustavi</button>":e.status==="failed"?"<button class=\"secondary\" onclick=\"executionAction('"+e.id+"','retry')\">Ponovi</button>":"";return "<div class=\"list-row\"><span><strong>"+e.operation+"</strong><br><small>"+(e.target||"sistem")+" · "+new Date(e.created_at).toLocaleString("sr-RS")+"</small></span><span>"+statusLabel(e.status)+" · "+(e.progress||0)+"%</span><span>"+actions+"</span></div>"}).join(""):"<div class=\"result\">Nema operacija.</div>"}
function renderWorkers(){var box=document.querySelector("#worker-list");box.innerHTML=workers.length?workers.map(function(w){return "<div class=\"list-row\"><span><strong>"+w.name+"</strong><br><small>"+w.worker_key+"</small></span><span>"+statusLabel(w.status)+"</span><small>"+(w.last_heartbeat?"Poslednji signal: "+new Date(w.last_heartbeat).toLocaleString("sr-RS"):"Nema signala")+"</small></div>"}).join(""):"<div class=\"result\">Nema registrovanih radnika.</div>"}
function renderQueue(){var box=document.querySelector("#queue-list");box.innerHTML=queue.length?queue.map(function(q){return "<div class=\"list-row\"><span><strong>"+(q.operation||"Operacija")+"</strong><br><small>Prioritet "+q.priority+"</small></span><span>"+statusLabel(q.status)+"</span></div>"}).join(""):"<div class=\"result\">Red čekanja je prazan.</div>"}
function renderOrchestrations(){var box=document.querySelector("#orchestration-list");if(!box)return;box.innerHTML=orchestrations.length?orchestrations.map(function(o){var badge=statusLabel(o.status);return "<div class=\"list-row\"><span><strong>"+o.name+"</strong><br><small>"+(o.trigger||"launcher")+" · "+new Date(o.created_at).toLocaleString("sr-RS")+"</small></span><span>"+badge+"</span><button class=\"secondary\" onclick=\"viewOrchestration('"+o.id+"')\">Detalji</button></div>"}).join(""):"<div class=\"result\">Nema orkestracija.</div>"}
function renderFlow(steps){var box=document.querySelector("#orchestration-flow");if(!box)return;box.innerHTML=(steps||[]).map(function(s,i){return "<div class=\"flow-node\"><span>"+(i+1)+"</span><strong>"+s.name+"</strong><small>"+statusLabel(s.status)+(s.parallel_group?" · paralelno":"")+"</small></div>"}).join("<div class=\"flow-arrow\">→</div>")||"<div class=\"result\">Nema koraka.</div>"}
function renderApprovals(items){var box=document.querySelector("#approval-list");if(!box)return;box.innerHTML=(items||[]).length?items.map(function(a){return "<div class=\"list-row\"><span><strong>"+a.name+"</strong><br><small>"+a.orchestration_name+"</small></span><span>"+(a.approval_status||"PENDING")+"</span><button class=\"secondary\" onclick=\"approveStep('"+a.id+"')\">Odobri</button></div>"}).join(""):"<div class=\"result\">Nema koraka koji čekaju odobrenje.</div>"}
async function loadApprovals(){try{var r=await fetch("../api/system/approval-center"),d=await r.json();if(r.ok)renderApprovals(d.approvals)}catch(e){}}
async function approveStep(id){try{var r=await fetch("../api/system/orchestration-approval",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({step_id:id,decision:"approve"})});if(!r.ok)throw Error("Odobrenje nije uspelo.");recordAudit("ORKESTRACIJA_KORAK_ODOBREN",{step_id:id});loadApprovals()}catch(e){recordAudit("APPROVAL_NEUSPEO",{message:e.message})}}
async function autonomousLaunch(){try{var r=await fetch("../api/system/autonomous-launcher",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({operation:"system_check",target:"development"})}),d=await r.json();if(!r.ok)throw Error(d.error||"Greška");document.querySelector("#autonomous-result").innerHTML="<span class=\"ok\">✓ Sistem je stavljen u kontrolisani red izvršavanja.</span>";recordAudit("AUTONOMOUS_LAUNCH",{execution_id:d.execution_id,mode:d.mode});loadQueue();loadExecutions()}catch(e){document.querySelector("#autonomous-result").innerHTML="<span class=\"warn\">! "+e.message+"</span>"}}
async function loadSchedules(){var box=document.querySelector("#schedule-list");box.innerHTML=schedules.length?schedules.map(function(s){return "<div class=\"list-row\"><span><strong>"+s.name+"</strong><br><small>"+s.operation+" · "+(s.cron_expression||"jednokratno")+"</small></span><span>"+(s.enabled?"AKTIVAN":"ISKLJUČEN")+"</span></div>"}).join(""):"<div class=\"result\">Nema zakazanih operacija.</div>"}
async function recordAudit(action,details){details=details||{};log(action);try{await fetch("../api/system/audit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:action,details:details})})}catch(e){}}
async function runFullCheck(){var box=document.querySelector("#launch-result");box.textContent="Proveravam backend…";try{var r=await fetch("../api/system/health"),d=await r.json();if(!r.ok)throw Error(d.error||"Greška");checks=d.checks||fallbackChecks;renderHealth();box.innerHTML="<span class=\"ok\">✓ Provera sistema je završena.</span>";recordAudit("PUNA_PROVERA_SISTEMA",{checks:checks})}catch(e){checks=fallbackChecks;renderHealth();box.innerHTML="<span class=\"warn\">! Backend provera nije dostupna.</span>";recordAudit("PROVERA_REZERVNI_REŽIM",{message:e.message})}}
async function queueSystemCheck(){try{var r=await fetch("../api/system/executions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({operation:"system_check",target:"development",payload:{source:"launcher"}})}),d=await r.json();if(!r.ok)throw Error(d.error||"Greška");await fetch("../api/system/queue",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({execution_id:d.execution.id,priority:90})});recordAudit("OPERACIJA_DODATA_U_RED",{execution_id:d.execution.id});await loadExecutions();await loadQueue();document.querySelector("#launch-result").innerHTML="<span class=\"ok\">✓ Operacija je dodata u red čekanja.</span>"}catch(e){recordAudit("DODAVANJE_OPERACIJE_NEUSPELO",{message:e.message})}}
async function loadExecutions(){try{var r=await fetch("../api/system/executions"),d=await r.json();if(r.ok){executions=d.executions||[];renderExecutions()}}catch(e){renderExecutions()}}
async function executionAction(id,action){try{var r=await fetch("../api/system/executions/"+id,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:action})}),d=await r.json();if(!r.ok)throw Error(d.error||"Greška");recordAudit("IZVRSENJE_"+action.toUpperCase(),{execution_id:id});await loadExecutions()}catch(e){recordAudit("IZVRSENJE_AKCIJA_NEUSPELA",{execution_id:id,action:action,message:e.message})}}
async function loadWorkers(){try{var r=await fetch("../api/system/workers"),d=await r.json();if(r.ok){workers=d.workers||[];renderWorkers()}}catch(e){renderWorkers()}}
async function registerWorker(){try{var r=await fetch("../api/system/workers",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({worker_key:"launcher-worker",name:"Marijana Worker",capabilities:["system","module","deployment"]})});if(!r.ok)throw Error("Greška");recordAudit("RADNIK_REGISTROVAN");await loadWorkers()}catch(e){recordAudit("REGISTRACIJA_RADNIKA_NEUSPESNA",{message:e.message})}}
async function loadQueue(){try{var r=await fetch("../api/system/queue"),d=await r.json();if(r.ok){queue=d.queue||[];renderQueue()}}catch(e){renderQueue()}}
async function loadOrchestrations(){try{var r=await fetch("../api/system/orchestrations"),d=await r.json();if(r.ok){orchestrations=d.orchestrations||[];renderOrchestrations()}}catch(e){renderOrchestrations()}}
async function createOrchestration(){try{var steps=[{step_key:"provera",name:"Provera sistema",action:"system_check",type:"action",checkpoint:true},{step_key:"zavisnosti",name:"Provera zavisnosti",action:"dependency_check",depends_on:["provera"]},{step_key:"approval",name:"Odobrenje za nastavak",type:"approval",depends_on:["zavisnosti"],approval_required:true},{step_key:"deployment",name:"Priprema deploymenta",action:"prepare_deployment",depends_on:["approval"],compensation_action:"deployment_rollback",checkpoint:true}];var r=await fetch("../api/system/orchestrator",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:"Master System Orchestrator",trigger:"launcher",payload:{source:"system_launcher"},steps:steps})}),d=await r.json();if(!r.ok)throw Error(d.error||"Greška");recordAudit("MASTER_ORKESTRACIJA_KREIRANA",{orchestration_id:d.orchestration_id,queued:d.queued});await loadOrchestrations();document.querySelector("#orchestration-result").innerHTML="<span class=\"ok\">✓ Orkestracija je kreirana.</span>"}catch(e){document.querySelector("#orchestration-result").innerHTML="<span class=\"warn\">! "+e.message+"</span>";recordAudit("MASTER_ORKESTRACIJA_NEUSPELA",{message:e.message})}}
async function viewOrchestration(id){try{var r=await fetch("../api/system/orchestrator?id="+encodeURIComponent(id)),d=await r.json();if(!r.ok)throw Error(d.error||"Greška");document.querySelector("#orchestration-result").innerHTML="<strong>"+d.orchestration.name+"</strong><br>"+d.steps.map(function(s){return s.position+". "+s.name+" — "+statusLabel(s.status)+(s.approval_required?" · odobrenje":"")}).join("<br>");renderFlow(d.steps)}catch(e){recordAudit("PREGLED_ORKESTRACIJE_NEUSPEO",{message:e.message})}}
async function loadSchedules(){try{var r=await fetch("../api/system/scheduler"),d=await r.json();if(r.ok){schedules=d.schedules||[];renderSchedules()}}catch(e){renderSchedules()}}
async function createSchedule(){try{var name=prompt("Naziv rasporeda","Dnevna sistemska provera");if(!name)return;var cron=prompt("Cron izraz","0 8 * * *");if(!cron)return;var r=await fetch("../api/system/scheduler",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:name,operation:"system_check",cron_expression:cron})});if(!r.ok)throw Error("Greška");recordAudit("RASPORED_KREIRAN",{name:name,cron:cron});await loadSchedules()}catch(e){recordAudit("RASPORED_NEUSPEO",{message:e.message})}}
async function loadModules(){try{var r=await fetch("../api/system/modules"),d=await r.json();if(r.ok&&d.modules){modules=d.modules;renderModules()}}catch(e){}}
async function loadModuleStates(){try{var r=await fetch("../api/system/module-state"),d=await r.json();if(r.ok){moduleStates=d.states||[];renderModules()}}catch(e){}}
async function moduleLifecycle(moduleId,action){try{var r=await fetch("../api/system/module-lifecycle",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({module_id:moduleId,action:action})}),d=await r.json();if(!r.ok)throw Error(d.error||"Greška");recordAudit("ŽIVOTNI_CIKLUS_MODULA",{module_id:moduleId,action:action,state:d.state});loadModuleStates()}catch(e){recordAudit("ŽIVOTNI_CIKLUS_NEUSPEO",{module_id:moduleId,action:action,message:e.message})}}
async function loadGraph(){try{var r=await fetch("../api/system/dependency-graph"),d=await r.json();if(r.ok)renderGraph(d)}catch(e){}}
async function loadAudit(){try{var r=await fetch("../api/system/audit"),d=await r.json();if(r.ok&&d.events){audit=d.events.map(function(x){return {time:new Date(x.created_at).toLocaleTimeString("sr-RS"),msg:x.action}});renderAudit()}}catch(e){}}
async function loadMigrations(){try{var r=await fetch("../api/system/migrations"),d=await r.json();if(r.ok){migrationData=d.migrations||[];renderMigrations()}}catch(e){renderMigrations()}}
async function loadReleases(){try{var r=await fetch("../api/system/releases"),d=await r.json();if(r.ok)renderReleases(d)}catch(e){}}
async function createDeploymentPlan(){var target=document.querySelector("#deploy-target").value,box=document.querySelector("#deploy-plan");box.innerHTML="<div class=\"result\">Kreiram plan…</div>";try{var r=await fetch("../api/system/deployment-plan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({target:target})}),d=await r.json();if(!r.ok)throw Error(d.error||"Greška");box.innerHTML=d.steps.map(function(s){return "<div class=\"list-row\"><span>"+s.name+"</span><span class=\"warn\">PROVERA</span></div>"}).join("");recordAudit("PLAN_DEPLOYMENTA_KREIRAN",{target:target,plan_id:d.plan_id})}catch(e){recordAudit("PLAN_DEPLOYMENTA_NEUSPEO",{message:e.message})}}
async function dependencyCheck(){try{var r=await fetch("../api/system/dependencies"),d=await r.json();recordAudit("PROVERA_ZAVISNOSTI",{ok:d.ok,missing:d.missing});return d}catch(e){return {ok:false,missing:[{module:"sistem",dependency:"dependency-api"}]}}}
async function smokeTests(){try{var r=await fetch("../api/system/smoke-tests"),d=await r.json();return d}catch(e){return {tests:[]}}}
async function prepareDeployment(){var deps=await dependencyCheck(),smoke=await smokeTests(),pending=migrationData.filter(function(m){return m.status!=="applied"}).length,blockers=checks.filter(function(c){return c.state!=="ready"}).length+(deps.missing||[]).length+(pending?1:0);document.querySelector("#launch-result").innerHTML=blockers?"<span class=\"warn\">DEPLOYMENT JE BLOKIRAN</span><br>"+blockers+" uslova još nije spremno.":"<span class=\"ok\">✓ DEPLOYMENT JE SPREMAN</span><br>Provere su prošle.";recordAudit("PROVERA_SPREMNOSTI_DEPLOYMENTA",{blockers:blockers,smoke_tests:(smoke.tests||[]).length})}
async function planRollback(){var release=prompt("Koju verziju želiš da pripremimo za rollback?","0.1.0");if(!release)return;var r=await fetch("../api/system/rollback",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({release:release})});document.querySelector("#rollback-result").innerHTML=r.ok?"<span class=\"ok\">✓ Rollback plan je pripremljen.</span>":"<span class=\"bad\">Rollback plan nije napravljen.</span>";recordAudit("ROLLBACK_PLAN_KREIRAN",{release:release,ok:r.ok})}
document.querySelectorAll(".nav").forEach(function(n){n.onclick=function(){document.querySelectorAll(".nav").forEach(function(x){x.classList.remove("active")});n.classList.add("active");document.querySelectorAll(".view").forEach(function(v){v.classList.remove("active")});document.querySelector("#view-"+n.dataset.view).classList.add("active");document.querySelector("#view-title").textContent=n.textContent.replace(/^[^\s]+\s/,"")}});
renderHealth();renderModules();renderMigrations();renderAudit();loadModules();loadModuleStates();loadGraph();loadAudit();loadMigrations();loadReleases();loadExecutions();loadWorkers();loadQueue();loadSchedules();loadOrchestrations();loadApprovals();