CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),name TEXT,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,plan TEXT NOT NULL DEFAULT 'free_trial',trial_started_at TIMESTAMPTZ DEFAULT NOW(),created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS projects (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,name TEXT NOT NULL,type TEXT NOT NULL DEFAULT 'product',status TEXT NOT NULL DEFAULT 'draft',data JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS assets (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,project_id UUID REFERENCES projects(id) ON DELETE SET NULL,name TEXT NOT NULL,mime_type TEXT,storage_key TEXT NOT NULL,size_bytes BIGINT,metadata JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS connections (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,provider TEXT NOT NULL,encrypted_data TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS usage_events (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,feature TEXT NOT NULL,quantity INTEGER NOT NULL DEFAULT 1,metadata JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS subscriptions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,provider TEXT NOT NULL,customer_id TEXT,subscription_id TEXT,plan TEXT NOT NULL,status TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS funnels (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,name TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'draft',data JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS drive_folders (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,parent_id UUID REFERENCES drive_folders(id) ON DELETE CASCADE,name TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
ALTER TABLE projects ADD COLUMN IF NOT EXISTS folder_id UUID REFERENCES drive_folders(id) ON DELETE SET NULL;
CREATE TABLE IF NOT EXISTS system_audit_log (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,action TEXT NOT NULL,details JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS system_deployments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,target TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'planned',plan JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_projects_user ON projects(user_id,updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_projects_folder ON projects(user_id,folder_id,updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_assets_user ON assets(user_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_usage_user ON usage_events(user_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_funnels_user ON funnels(user_id,updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_drive_folders_user ON drive_folders(user_id,updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_drive_folders_parent ON drive_folders(user_id,parent_id);
CREATE INDEX IF NOT EXISTS idx_system_audit_user_time ON system_audit_log(user_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_system_deployments_user ON system_deployments(user_id,created_at DESC);

CREATE TABLE IF NOT EXISTS system_executions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,operation TEXT NOT NULL,target TEXT,status TEXT NOT NULL DEFAULT 'queued',progress INTEGER NOT NULL DEFAULT 0,payload JSONB NOT NULL DEFAULT '{}'::jsonb,result JSONB NOT NULL DEFAULT '{}'::jsonb,error TEXT,attempts INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),started_at TIMESTAMPTZ,finished_at TIMESTAMPTZ,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS system_execution_steps (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),execution_id UUID NOT NULL REFERENCES system_executions(id) ON DELETE CASCADE,step_key TEXT NOT NULL,name TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'queued',position INTEGER NOT NULL DEFAULT 0,progress INTEGER NOT NULL DEFAULT 0,detail TEXT,attempts INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS system_workers (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,worker_key TEXT NOT NULL,name TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'idle',capabilities JSONB NOT NULL DEFAULT '[]'::jsonb,last_heartbeat TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(user_id,worker_key));
CREATE TABLE IF NOT EXISTS system_queue (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,execution_id UUID REFERENCES system_executions(id) ON DELETE CASCADE,priority INTEGER NOT NULL DEFAULT 50,status TEXT NOT NULL DEFAULT 'queued',available_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),attempts INTEGER NOT NULL DEFAULT 0,locked_at TIMESTAMPTZ,locked_by UUID,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS system_schedules (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,name TEXT NOT NULL,operation TEXT NOT NULL,cron_expression TEXT,enabled BOOLEAN NOT NULL DEFAULT TRUE,payload JSONB NOT NULL DEFAULT '{}'::jsonb,last_run_at TIMESTAMPTZ,next_run_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS system_orchestrations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,name TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'planned',trigger TEXT,payload JSONB NOT NULL DEFAULT '{}'::jsonb,result JSONB NOT NULL DEFAULT '{}'::jsonb,error TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),started_at TIMESTAMPTZ,finished_at TIMESTAMPTZ,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS system_orchestration_steps (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),orchestration_id UUID NOT NULL REFERENCES system_orchestrations(id) ON DELETE CASCADE,step_key TEXT NOT NULL,name TEXT NOT NULL,type TEXT NOT NULL DEFAULT 'action',action TEXT,position INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'queued',condition JSONB NOT NULL DEFAULT '{}'::jsonb,depends_on JSONB NOT NULL DEFAULT '[]'::jsonb,parallel_group TEXT,input JSONB NOT NULL DEFAULT '{}'::jsonb,output JSONB NOT NULL DEFAULT '{}'::jsonb,retry_policy JSONB NOT NULL DEFAULT '{}'::jsonb,checkpoint BOOLEAN NOT NULL DEFAULT FALSE,compensation_action TEXT,approval_required BOOLEAN NOT NULL DEFAULT FALSE,approval_status TEXT,approved_by UUID REFERENCES users(id) ON DELETE SET NULL,approved_at TIMESTAMPTZ,started_at TIMESTAMPTZ,finished_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(orchestration_id,step_key));
CREATE TABLE IF NOT EXISTS system_checkpoints (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,orchestration_id UUID NOT NULL REFERENCES system_orchestrations(id) ON DELETE CASCADE,step_id UUID REFERENCES system_orchestration_steps(id) ON DELETE CASCADE,name TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'saved',state JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_system_orchestrations_user ON system_orchestrations(user_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_system_orchestration_steps_order ON system_orchestration_steps(orchestration_id,position);
CREATE INDEX IF NOT EXISTS idx_system_checkpoints_orchestration ON system_checkpoints(orchestration_id,created_at DESC);


CREATE TABLE IF NOT EXISTS system_orchestration_events (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,orchestration_id UUID REFERENCES system_orchestrations(id) ON DELETE CASCADE,step_id UUID REFERENCES system_orchestration_steps(id) ON DELETE SET NULL,event_type TEXT NOT NULL,payload JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS system_policies (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID REFERENCES users(id) ON DELETE CASCADE,name TEXT NOT NULL,scope TEXT NOT NULL DEFAULT 'system',rules JSONB NOT NULL DEFAULT '{}'::jsonb,enabled BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS system_decision_gates (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,orchestration_id UUID REFERENCES system_orchestrations(id) ON DELETE CASCADE,step_id UUID REFERENCES system_orchestration_steps(id) ON DELETE SET NULL,decision TEXT NOT NULL DEFAULT 'pending',rationale JSONB NOT NULL DEFAULT '{}'::jsonb,requires_human BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),decided_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS system_recovery_actions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,execution_id UUID REFERENCES system_executions(id) ON DELETE CASCADE,orchestration_id UUID REFERENCES system_orchestrations(id) ON DELETE CASCADE,action TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'planned',attempt INTEGER NOT NULL DEFAULT 0,result JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS system_runtime_registry (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID REFERENCES users(id) ON DELETE CASCADE,capability_key TEXT NOT NULL,layer TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'planned',config JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(user_id,capability_key));
CREATE INDEX IF NOT EXISTS idx_system_orch_events_user_time ON system_orchestration_events(user_id,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_system_runtime_registry_user ON system_runtime_registry(user_id,status);


-- Marijana Mockup Studio
CREATE TABLE IF NOT EXISTS mockup_projects (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,name TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'draft',scene JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS mockup_templates (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID REFERENCES users(id) ON DELETE CASCADE,name TEXT NOT NULL,category TEXT NOT NULL,template_type TEXT NOT NULL,config JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS mockup_assets (id UUID PRIMARY KEY DEFAULT gen_random_uuid(),user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,project_id UUID REFERENCES mockup_projects(id) ON DELETE CASCADE,name TEXT NOT NULL,asset_type TEXT NOT NULL,storage_key TEXT,metadata JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS idx_mockup_projects_user ON mockup_projects(user_id,updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_mockup_templates_category ON mockup_templates(category);
CREATE INDEX IF NOT EXISTS idx_mockup_assets_project ON mockup_assets(project_id,created_at DESC);
