let objects=[],selected=-1,drag=null,viewMode='2d';
let history=[],historyIndex=-1,isRestoring=false,clipboard=null,stageZoom=1,snapEnabled=true;
const fontLibrary=['Arial','Georgia','Times New Roman','Verdana','Courier New','Inter','Montserrat','DM Sans','Poppins','Playfair Display','Cormorant Garamond','Libre Baskerville','Merriweather','Lora','Bodoni Moda','DM Serif Display','Cinzel','Prata','Abril Fatface','Bebas Neue','Oswald','Roboto','Roboto Slab','Open Sans','Nunito','Raleway','Work Sans','Manrope','Space Grotesk','Orbitron','JetBrains Mono','Fira Code','Pacifico','Dancing Script','Great Vibes','Lobster','Satisfy','Caveat','Permanent Marker','UnifrakturCook'];
function snapshot(){return JSON.stringify({objects,selected,viewMode})}
function commitHistory(){if(isRestoring)return;const s=snapshot();if(history[historyIndex]===s)return;history=history.slice(0,historyIndex+1);history.push(s);if(history.length>60)history.shift();historyIndex=history.length-1}
function restoreSnapshot(s){isRestoring=true;const v=JSON.parse(s);objects=v.objects||[];selected=v.selected??-1;viewMode=v.viewMode||'2d';isRestoring=false;render()}
function undo(){if(historyIndex>0){historyIndex--;restoreSnapshot(history[historyIndex])}}
function redo(){if(historyIndex<history.length-1){historyIndex++;restoreSnapshot(history[historyIndex])}}
const scene=document.getElementById('scene'),imgInput=document.getElementById('imageInput');
const presets={phone:{type:'phone',x:255,y:85,w:190,h:380,r:0,rx:0,ry:0,depth:25,perspective:1200},tablet:{type:'tablet',x:200,y:55,w:320,h:450,r:0,rx:0,ry:0,depth:25,perspective:1200},frame:{type:'frame',x:215,y:80,w:290,h:370,r:0,rx:0,ry:0,depth:35,perspective:1200},desk:{type:'phone',x:470,y:110,w:170,h:340,r:0,rx:5,ry:-18,depth:45,perspective:1000},wall:{type:'frame',x:230,y:80,w:290,h:370,r:-2,rx:0,ry:-12,depth:35,perspective:1100},minimal:{type:'poster',x:250,y:75,w:250,h:350,r:0,rx:0,ry:0,depth:10,perspective:1200},'3d':{type:'scene3d',x:230,y:180,w:260,h:180,r:0,rx:12,ry:-22,depth:70,perspective:900},webwall:{type:'panel3d',x:180,y:90,w:250,h:360,r:0,rx:0,ry:-22,depth:25,perspective:950},isometric:{type:'panel3d',x:210,y:100,w:280,h:210,r:0,rx:58,ry:-32,depth:55,perspective:850}};
const magazineStyles={40:{name:'1940s Classic Editorial',font:'Georgia',color:'#4b3828',bg:'#e8dcc7',accent:'#8b6b42',filter:'sepia(.35) contrast(.95)',border:'8px double #8b6b42',layout:'classic'},50:{name:'1950s Mid-Century',font:'Georgia',color:'#20364a',bg:'#f1e7cf',accent:'#c65b3d',filter:'saturate(.8) contrast(1.05)',border:'6px solid #c65b3d',layout:'midcentury'},60:{name:'1960s Pop Editorial',font:'Arial',color:'#111',bg:'#f4df45',accent:'#e94d35',filter:'saturate(1.25) contrast(1.08)',border:'5px solid #111',layout:'pop'},70:{name:'1970s Retro',font:'Georgia',color:'#432d20',bg:'#d88b52',accent:'#efc15a',filter:'sepia(.2) saturate(.9)',border:'9px solid #432d20',layout:'retro'},80:{name:'1980s Bold Glam',font:'Arial',color:'#fff',bg:'#24143f',accent:'#ff4fa3',filter:'saturate(1.35) contrast(1.12)',border:'6px solid #ff4fa3',layout:'glam'},90:{name:'1990s Minimal Editorial',font:'Arial',color:'#111',bg:'#f4f4f0',accent:'#d62828',filter:'contrast(1.08)',border:'3px solid #111',layout:'minimal'},20:{name:'2020s Digital Editorial',font:'Arial',color:'#101522',bg:'#f5f0e8',accent:'#63c8ff',filter:'saturate(1.05)',border:'2px solid #101522',layout:'digital'},27:{name:'2027 Future Editorial',font:'Arial',color:'#f7f4eb',bg:'#11182f',accent:'#63c8ff',filter:'contrast(1.15) saturate(1.2)',border:'2px solid #63c8ff',layout:'future'}};
function uid(){return Math.random().toString(36).slice(2)}
function addObject(type,extra={}){const o={id:uid(),type,x:120+objects.length*18,y:80+objects.length*12,w:200,h:220,r:0,rx:0,ry:0,depth:25,perspective:1200,color:'#63c8ff',src:null,fit:'contain',zoom:1,ox:0,oy:0,text:'Tekst',fontFamily:'Arial',fontSize:42,fontWeight:700,fontStyle:'normal',letterSpacing:0,bevel:0,metallic:0,gloss:35,opacity:1,effects:{},...extra};if(presets[type])Object.assign(o,presets[type],extra);objects.push(o);selected=objects.length-1;render();commitHistory()}
function addText(text='Tekst'){addObject('text',{text,w:Math.max(180,text.length*28),h:90,depth:35,fontSize:42,fontWeight:700,color:'#d9b66f'})}
function addMagazine(){addObject('magazine',{w:300,h:400,style:'20',magazineStyle:20})}
function applyMagazineStyle(year){if(selected<0)return;const o=objects[selected];if(!['magazine','planner','poster','book','card'].includes(o.type)){o.type='magazine';o.w=300;o.h=400}const s=magazineStyles[year];o.magazineStyle=year;o.style=String(year);o.magazineTheme={...s};o.color=s.accent;o.effects=o.effects||{};o.effects.magazine=true;o.effects.magazineFilter=s.filter;render();commitHistory()}
function imageTag(o,cls=''){if(!o.src)return '';const fit=o.fit==='cover'?'cover':(o.fit==='crop'?'cover':'contain'),z=o.zoom||1,x=o.ox||0,y=o.oy||0;return '<img class="'+cls+' '+fit+'" src="'+o.src+'" style="transform:translate('+x+'%,'+y+'%) scale('+z+');">'}
function effectStyle(o){const e=o.effects||{},s=[];let f=[];if(e.shadow)s.push((e.shadowX||0)+'px '+(e.shadowY||12)+'px '+(e.shadowBlur||25)+'px '+(e.shadowColor||'rgba(0,0,0,.28)'));if(e.glow)s.push('0 0 '+(e.glowBlur||24)+'px '+(e.glowColor||'rgba(99,200,255,.75)'));if(e.outline)f.push('drop-shadow(0 0 '+(e.outlineSize||2)+'px '+(e.outlineColor||'#fff'));if(e.blur)f.push('blur('+(e.blur||2)+'px)');if(e.grayscale)f.push('grayscale(1)');if(e.sepia)f.push('sepia(.8)');if(e.vintage)f.push('contrast(.9) saturate(.75) sepia(.2)');if(e.duotone)f.push('contrast(1.15) saturate(1.3)');if(e.magazineFilter)f.push(e.magazineFilter);return 'box-shadow:'+s.join(',')+';filter:'+f.join(' ')+';backdrop-filter:'+(e.glass?'blur(10px)':'none')+';'}
function textStyle(o){const shadow=Math.max(0,o.depth||0),bevel=Math.min(18,o.bevel||0),layers=Math.min(10,Math.ceil(shadow/8));let shadows=[];for(let i=1;i<=layers;i++)shadows.push((i*1.5)+'px '+(i*1.5)+'px 0 '+o.color);if(o.effects?.shadow)shadows.push('0 12px 24px rgba(0,0,0,.3)');if(o.effects?.glow)shadows.push('0 0 22px '+(o.effects.glowColor||o.color));return 'font-family:'+o.fontFamily+';font-size:'+o.fontSize+'px;font-weight:'+o.fontWeight+';font-style:'+o.fontStyle+';letter-spacing:'+o.letterSpacing+'px;color:'+o.color+';opacity:'+o.opacity+';text-shadow:'+shadows.join(',')+';--bevel:'+bevel+'px'}
function magazineMarkup(o){const s=o.magazineTheme||magazineStyles[o.magazineStyle]||magazineStyles[20];const title=o.magazineTitle||'MAGAZINE';return '<div class="mag-cover-head" style="font-family:'+s.font+';color:'+s.color+';background:'+s.bg+';border:'+s.border+'"><small style="color:'+s.accent+'">'+(o.magazineStyle||20)+' EDITION</small><strong>'+title+'</strong><em>EDITORIAL • CULTURE • STYLE</em>'+imageTag(o,'mag-cover-image')+'</div>'}
function markup(o,i){let inner='';if(['phone','tablet','laptop','monitor'].includes(o.type))inner='<div class="screen">'+imageTag(o)+'</div>';else if(['frame','roundFrame','ovalFrame','magazine','planner','poster','book','card','mug','bottle','bag','tshirt','hoodie','box','notebook','sticker'].includes(o.type))inner=o.type==='magazine'&&o.magazineTheme?magazineMarkup(o):'<div class="art">'+imageTag(o)+'</div>';else if(['image','panel3d','wall3d'].includes(o.type))inner=imageTag(o);else if(o.type==='text'||o.type==='text3d')inner='<span class="text-3d-render '+(o.type==='text3d'?'is-3d':'')+'" style="'+(o.type==='text3d'?text3DStyle(o):textStyle(o))+'">'+(o.text||'Tekst')+'</span>';const classes=['obj',o.type,i===selected?'selected':''].filter(Boolean).join(' ');const materialAttr=o.material?' data-material="'+o.material+'"':'';const transform='perspective('+o.perspective+'px) rotateX('+o.rx+'deg) rotateY('+o.ry+'deg) rotateZ('+o.r+'deg) translateZ('+o.depth+'px)';const bg=['shape','circle'].includes(o.type)?o.color:'';return '<div class="'+classes+'" data-i="'+i+'"'+materialAttr+' style="display:'+(o.hidden?'none':'block')+';left:'+o.x+'px;top:'+o.y+'px;width:'+o.w+'px;height:'+o.h+'px;transform:'+transform+';background:'+bg+';'+effectStyle(o)+'">'+inner+(i===selected?'<i class="resize-handle nw" data-dir="nw"></i><i class="resize-handle ne" data-dir="ne"></i><i class="resize-handle sw" data-dir="sw"></i><i class="resize-handle se" data-dir="se"></i>':'')+'</div>'}



function buildScene(k){objects=[];selected=-1;const add=(type,p)=>addObject(type,p);if(k==='device-trio'){add('phone',{x:80,y:90,w:170,h:340,ry:16,depth:20});add('tablet',{x:275,y:60,w:250,h:360,ry:-6,depth:45});add('laptop',{x:360,y:365,w:300,h:190,ry:-10,depth:15})}if(k==='creator-desk'){add('laptop',{x:235,y:80,w:390,h:245,ry:-4,depth:30});add('phone',{x:90,y:210,w:150,h:300,ry:14,depth:70});add('mug',{x:570,y:325,w:150,h:120,ry:-8,depth:45});add('notebook',{x:40,y:390,w:210,h:130,ry:10,depth:25})}if(k==='product-line'){add('box',{x:80,y:190,w:210,h:155,ry:8,depth:30});add('bottle',{x:300,y:120,w:100,h:280,ry:-5,depth:55});add('mug',{x:430,y:205,w:190,h:145,ry:8,depth:40});add('bag',{x:545,y:100,w:150,h:230,ry:-12,depth:20})}if(k==='floating-pages'){for(let i=0;i<4;i++)add('panel3d',{x:90+i*145,y:90+i*28,w:260,h:190,rx:8+i*3,ry:-16+i*9,depth:20+i*35})}if(k==='social-wall'){for(let i=0;i<6;i++)add('phone',{x:40+(i%3)*220,y:45+Math.floor(i/3)*270,w:145,h:255,ry:(i%2?10:-8),depth:i*8})}if(k==='brand-showcase'){add('frame',{x:55,y:75,w:250,h:320,ry:-8,depth:25});add('phone',{x:290,y:95,w:160,h:320,ry:8,depth:60});add('box',{x:480,y:160,w:210,h:155,ry:-5,depth:35});addText('MARIJANA',{x:250,y:440,w:300,h:55,depth:18})}viewMode='3d';document.getElementById('stage').classList.add('mode-3d');render();commitHistory()}
function arrangeScene(mode){if(!objects.length)return;objects.forEach((o,i)=>{if(mode==='row'){o.x=25+i*125;o.y=190}if(mode==='grid'){o.x=40+(i%3)*230;o.y=60+Math.floor(i/3)*240}if(mode==='arc'){const a=(i-(objects.length-1)/2)*18;o.x=330+i*5;o.y=180+Math.abs(a)*2;o.ry=a}if(mode==='depth'){o.x=80+i*95;o.y=100+i*35;o.depth=i*35;o.ry=(i-objects.length/2)*7}});render();commitHistory()}
function setCamera(mode){const stage=document.getElementById('stage');const scene=document.getElementById('scene');scene.dataset.camera=mode;stage.dataset.camera=mode;render();}
function setLighting(mode){const stage=document.getElementById('stage');stage.dataset.lighting=mode;render();}
function setMaterial(mode){if(selected<0)return;objects[selected].material=mode;render();commitHistory()}
function setMapping(mode){if(selected<0)return;const o=objects[selected];o.mapping=mode;o.mappingMode=mode;if(mode==='screen'){o.fit=o.fit||'contain'}if(mode==='frame'){o.fit=o.fit||'contain'}if(mode==='product'){o.fit=o.fit||'contain'}render();commitHistory()}
function setMappingFit(mode){if(selected<0)return;objects[selected].fit=mode;render();commitHistory()}
function setMappingZoom(v){if(selected<0)return;objects[selected].zoom=+v;render()}
function setMappingOffset(axis,v){if(selected<0)return;objects[selected][axis==='x'?'ox':'oy']=+v;render()}
function setSurfaceWarp(mode){if(selected<0)return;const o=objects[selected];o.surfaceWarp=mode;if(mode==='flat'){o.surfaceRX=0;o.surfaceRY=0;o.surfaceCurve=0}if(mode==='tilt'){o.surfaceRX=o.rx||8;o.surfaceRY=o.ry||-12;o.surfaceCurve=0}if(mode==='perspective'){o.surfaceRX=o.rx||10;o.surfaceRY=o.ry||-20;o.surfaceCurve=0}if(mode==='curve'){o.surfaceCurve=12}render();commitHistory()}
function render(){scene.innerHTML=objects.map(markup).join('');scene.querySelectorAll('.obj').forEach(el=>{el.addEventListener('pointerdown',startDrag);el.addEventListener('click',()=>{selected=Number(el.dataset.i);renderInspector();renderLayers()});el.querySelectorAll('.resize-handle').forEach(h=>h.addEventListener('pointerdown',startResize))});renderInspector();renderLayers()}
function startResize(e){e.stopPropagation();const h=e.currentTarget,el=h.parentElement;selected=Number(el.dataset.i);const o=objects[selected],dir=h.dataset.dir,start={x:e.clientX,y:e.clientY,w:o.w,h:o.h,x0:o.x,y0:o.y};h.setPointerCapture?.(e.pointerId);const move=ev=>{const dx=ev.clientX-start.x,dy=ev.clientY-start.y;const min=30;if(dir.includes('e'))o.w=Math.max(min,start.w+dx);if(dir.includes('s'))o.h=Math.max(min,start.h+dy);if(dir.includes('w')){o.w=Math.max(min,start.w-dx);o.x=start.x0+(start.w-o.w)}if(dir.includes('n')){o.h=Math.max(min,start.h-dy);o.y=start.y0+(start.h-o.h)}render()};const up=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);commitHistory()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}
function startDrag(e){const el=e.currentTarget;selected=Number(el.dataset.i);const o=objects[selected];if(o.locked){e.preventDefault();return}drag={sx:e.clientX,sy:e.clientY,x:o.x,y:o.y};el.setPointerCapture?.(e.pointerId);window.onpointermove=ev=>{if(!drag)return;o.x=drag.x+(ev.clientX-drag.sx);o.y=drag.y+(ev.clientY-drag.sy);if(snapEnabled){o.x=Math.round(o.x/10)*10;o.y=Math.round(o.y/10)*10}render()};window.onpointerup=()=>{drag=null;window.onpointermove=null;commitHistory()}}
function renderInspector(){const o=objects[selected];document.getElementById('emptyInspector').classList.toggle('hidden',!o);document.getElementById('inspectorForm').classList.toggle('hidden',!o);if(!o)return;const values={objName:o.type,objX:o.x,objY:o.y,objW:o.w,objH:o.h,objR:o.r,objRX:o.rx,objRY:o.ry,objPerspective:o.perspective,objDepth:o.depth,objFit:o.fit,objZoom:o.zoom,objOX:o.ox,objOY:o.oy,objColor:o.color,objText:o.text,objFont:o.fontFamily,objFontSize:o.fontSize,objWeight:o.fontWeight,objStyle:o.fontStyle,objLetter:o.letterSpacing,objBevel:o.bevel,objGloss:o.gloss,objMetallic:o.metallic,objOpacity:o.opacity};for(const[id,val]of Object.entries(values)){const el=document.getElementById(id);if(el)el.value=val}const tf=document.getElementById('textControls');if(tf)tf.classList.toggle('hidden',!(o.type==='text'||o.type==='text3d'))}
function applyInspector(){const o=objects[selected];if(!o)return;o.x=+objX.value;o.y=+objY.value;o.w=+objW.value;o.h=+objH.value;o.r=+objR.value;o.rx=+objRX.value;o.ry=+objRY.value;o.perspective=+objPerspective.value;o.depth=+objDepth.value;o.fit=objFit.value;o.zoom=+objZoom.value;o.ox=+objOX.value;o.oy=+objOY.value;o.color=objColor.value;o.text=objText?.value||o.text;o.fontFamily=objFont?.value||o.fontFamily;o.fontSize=+objFontSize?.value||o.fontSize;o.fontWeight=+objWeight?.value||o.fontWeight;o.fontStyle=objStyle?.value||o.fontStyle;o.letterSpacing=+objLetter?.value||0;o.bevel=+objBevel?.value||0;o.gloss=+objGloss?.value||0;o.metallic=+objMetallic?.value||0;o.opacity=+objOpacity?.value||1;render();commitHistory()}
function applyEffect(type){if(selected<0)return;const o=objects[selected];o.effects=o.effects||{};if(type==='shadow')o.effects.shadow=true;if(type==='glow')o.effects.glow=true;if(type==='soft')Object.assign(o.effects,{shadow:true,shadowBlur:35,shadowY:16,shadowColor:'rgba(0,0,0,.18)'});if(type==='reflection')o.effects.reflection=true;if(type==='glass')o.effects.glass=true;if(type==='metal')o.effects.metal=true;if(type==='gold')o.effects.gold=true;if(type==='neon')Object.assign(o.effects,{glow:true,glowBlur:32,glowColor:o.color||'#63c8ff'});if(type==='emboss')o.effects.emboss=true;if(type==='outline')Object.assign(o.effects,{outline:true,outlineSize:2,outlineColor:'#fff'});if(type==='blur')o.effects.blur=3;if(type==='grayscale')o.effects.grayscale=true;if(type==='sepia')o.effects.sepia=true;if(type==='vintage')o.effects.vintage=true;if(type==='duotone')o.effects.duotone=true;render();commitHistory()}
function clearEffects(){if(selected<0)return;objects[selected].effects={};render();commitHistory()}
function setViewMode(mode){viewMode=mode;scene.dataset.view=mode;document.getElementById('stage').classList.toggle('mode-3d',mode==='3d');render();commitHistory()}
function rotateSelected(n){if(selected<0)return;objects[selected].r+=n;render();commitHistory()}function rotateAxis(axis,n){if(selected<0)return;objects[selected]['r'+axis.toUpperCase()]+=n;render();commitHistory()}function alignSelected(axis,mode){if(selected<0)return;const o=objects[selected];if(axis==='x')o.x=mode==='center'?(720-o.w)/2:mode==='start'?20:700-o.w;if(axis==='y')o.y=mode==='center'?(560-o.h)/2:mode==='start'?20:540-o.h;render();commitHistory()}function bringFront(){if(selected<0)return;const o=objects.splice(selected,1)[0];objects.push(o);selected=objects.length-1;render();commitHistory()}function sendBack(){if(selected<0)return;const o=objects.splice(selected,1)[0];objects.unshift(o);selected=0;render();commitHistory()}function renderLayers(){const el=document.getElementById('layerList');if(!el)return;el.innerHTML=objects.map((o,i)=>'<button class="layer-item '+(i===selected?'layer-active':'')+'" onclick="selected='+i+';render()">'+(i+1)+'. '+(o.text||o.type)+'</button>').join('')}function copySelected(){if(selected<0)return;clipboard=JSON.parse(JSON.stringify(objects[selected]))}function pasteSelected(){if(!clipboard)return;const o=JSON.parse(JSON.stringify(clipboard));o.id=uid();o.x+=25;o.y+=25;objects.push(o);selected=objects.length-1;render();commitHistory()}function toggleLock(){if(selected<0)return;objects[selected].locked=!objects[selected].locked;render();commitHistory()}function toggleVisibility(){if(selected<0)return;objects[selected].hidden=!objects[selected].hidden;render();commitHistory()}function deleteSelected(){if(selected<0)return;objects.splice(selected,1);selected=Math.min(selected,objects.length-1);render();commitHistory()}function resetScene(){objects=[];selected=-1;addObject('phone');render()}
function loadTemplate(k){const p=presets[k];if(!p)return;objects=[];addObject(p.type,p);if(k==='desk')addObject('shape',{x:100,y:470,w:520,h:35,color:'#8ea386'});if(k==='3d')addObject('shape',{x:170,y:390,w:390,h:30,color:'#d9b66f'});if(k==='webwall'){addObject('panel3d',{x:450,y:110,w:250,h:360,ry:22,depth:25});addObject('panel3d',{x:320,y:105,w:250,h:360,depth:20})}if(k==='isometric'){addObject('panel3d',{x:430,y:140,w:250,h:200,rx:58,ry:30,depth:45});addObject('panel3d',{x:120,y:300,w:280,h:210,rx:58,ry:28,depth:45})}render()}
function duplicateScene(){const copy=objects.map(o=>({...o,id:uid(),effects:{...(o.effects||{})},x:o.x+20,y:o.y+20}));objects.push(...copy);render();commitHistory()}function showPanel(name){document.querySelectorAll('.panel-view').forEach(x=>x.classList.add('hidden'));document.getElementById('panel-'+name).classList.remove('hidden')}function filterFonts(q){document.querySelectorAll('#fontLibrary button[data-font]').forEach(b=>b.style.display=b.dataset.font.toLowerCase().includes(q.toLowerCase())?'':'none')}function chooseFont(f){if(selected<0)return;objects[selected].fontFamily=f;render();commitHistory()}function filterLibrary(q){document.querySelectorAll('#panel-mockups button[data-name]').forEach(b=>b.style.display=b.dataset.name.includes(q.toLowerCase())?'':'none')}function keyboardShortcuts(e){if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='c'){e.preventDefault();copySelected();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='v'){e.preventDefault();pasteSelected();return}if(e.key==='Delete')deleteSelected();if(!objects[selected])return;const o=objects[selected],step=e.shiftKey?10:2;if(e.key==='ArrowLeft'){e.preventDefault();o.x-=step}if(e.key==='ArrowRight'){e.preventDefault();o.x+=step}if(e.key==='ArrowUp'){e.preventDefault();o.y-=step}if(e.key==='ArrowDown'){e.preventDefault();o.y+=step}render();commitHistory()}document.addEventListener('keydown',keyboardShortcuts)
function setStageZoom(v){stageZoom=+v;scene.style.setProperty('--stage-scale',stageZoom);render()}function toggleSnap(){snapEnabled=!snapEnabled;document.getElementById('snapBtn').textContent=snapEnabled?'Snap ON':'Snap OFF'}function setStageBackground(v){document.getElementById('stage').style.background=v}function exportSceneData(){const blob=new Blob([JSON.stringify({version:2,viewMode,objects},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='marijana-mockup-scene.json';a.click();URL.revokeObjectURL(a.href)}function saveMockup(){localStorage.setItem('marijana-mockup-draft',JSON.stringify({viewMode,objects}));commitHistory();alert('Mockup sačuvan kao radna verzija.')}function loadSavedMockup(){const s=localStorage.getItem('marijana-mockup-draft');if(!s)return;try{const v=JSON.parse(s);objects=v.objects||[];viewMode=v.viewMode||'2d';selected=objects.length?0:-1;render();commitHistory()}catch(e){alert('Radna verzija nije mogla da se učita.')}}imgInput.addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{if(selected>=0)objects[selected].src=reader.result;else addObject('image',{src:reader.result,x:180,y:100,w:300,h:300});render()};reader.readAsDataURL(f)});document.getElementById('scale').addEventListener('input',e=>{if(selected>=0){const o=objects[selected],s=+e.target.value;o.baseW=o.baseW||o.w;o.baseH=o.baseH||o.h;o.w=o.baseW*s;o.h=o.baseH*s;render()}});if(localStorage.getItem('marijana-mockup-draft'))loadSavedMockup();else{resetScene();commitHistory();}