let objects=[],selected=-1,drag=null;const scene=document.getElementById('scene');const imgInput=document.getElementById('imageInput');
const presets={phone:{type:'phone',x:255,y:85,w:190,h:380,r:0,depth:25},tablet:{type:'tablet',x:200,y:55,w:320,h:450,r:0,depth:25},frame:{type:'frame',x:215,y:80,w:290,h:370,r:0,depth:35},desk:{type:'phone',x:470,y:110,w:170,h:340,r:8,depth:45},wall:{type:'frame',x:230,y:80,w:290,h:370,r:-2,depth:35},minimal:{type:'poster',x:250,y:75,w:250,h:350,r:0,depth:10},'3d':{type:'scene3d',x:230,y:180,w:260,h:180,r:0,depth:70}};
function uid(){return Math.random().toString(36).slice(2)}
function addObject(type,extra={}){const o={id:uid(),type,x:120+objects.length*18,y:80+objects.length*12,w:200,h:220,r:0,depth:25,color:'#63c8ff',src:null,...extra};if(['phone','tablet','laptop','poster','frame','book','card','device'].includes(type)){o.w=presets[type]?.w||o.w;o.h=presets[type]?.h||o.h}objects.push(o);selected=objects.length-1;render()}
function markup(o,i){let inner='';if(o.type==='phone')inner='<div class="screen">'+(o.src?'<img src="'+o.src+'">':'')+'</div>';if(o.type==='tablet'||o.type==='laptop')inner='<div class="screen">'+(o.src?'<img src="'+o.src+'">':'')+'</div>';if(o.type==='frame')inner='<div class="art">'+(o.src?'<img src="'+o.src+'">':'')+'</div>';if(o.type==='poster')inner=o.src?'<img src="'+o.src+'">':'';if(o.type==='book')inner=o.src?'<img src="'+o.src+'">':'';if(o.type==='card')inner=o.src?'<img src="'+o.src+'">':'';if(o.type==='image')inner=o.src?'<img src="'+o.src+'">':'';if(o.type==='text')inner=o.text||'Tekst';if(o.type==='shape')inner='';if(o.type==='line')inner='';return '<div class="obj '+(o.type==='shape'?'shape ':'')+(o.type==='text'?'textObj ':'')+(o.type==='line'?'line ':'')+(o.type==='scene3d'?'scene3d ':'')+(o.type==='phone'?'phone ':'')+(o.type==='tablet'?'tablet ':'')+(o.type==='laptop'?'laptop ':'')+(o.type==='poster'?'poster ':'')+(o.type==='frame'?'frame ':'')+(o.type==='book'?'book ':'')+(o.type==='card'?'card ':'')+(i===selected?'selected ':'')+'" data-i="'+i+'" style="left:'+o.x+'px;top:'+o.y+'px;width:'+o.w+'px;height:'+o.h+'px;transform:rotate('+o.r+'deg) translateZ('+o.depth+'px);background:'+(o.type==='shape'?o.color:'')+'">'+inner+'</div>'}
function render(){scene.innerHTML=objects.map(markup).join('');scene.querySelectorAll('.obj').forEach(el=>{el.addEventListener('pointerdown',startDrag);el.addEventListener('click',()=>{selected=Number(el.dataset.i);renderInspector()})});renderInspector()}
function startDrag(e){const el=e.currentTarget;selected=Number(el.dataset.i);const o=objects[selected];drag={sx:e.clientX,sy:e.clientY,x:o.x,y:o.y};el.setPointerCapture?.(e.pointerId);window.onpointermove=ev=>{if(!drag)return;o.x=drag.x+(ev.clientX-drag.sx);o.y=drag.y+(ev.clientY-drag.sy);render()};window.onpointerup=()=>{drag=null;window.onpointermove=null}}
function renderInspector(){const o=objects[selected];document.getElementById('emptyInspector').classList.toggle('hidden',!o);document.getElementById('inspectorForm').classList.toggle('hidden',!o);if(!o)return;for(const [id,val] of [['objName',o.type],['objX',o.x],['objY',o.y],['objW',o.w],['objH',o.h],['objR',o.r],['objColor',o.color]])document.getElementById(id).value=val}
function applyInspector(){const o=objects[selected];if(!o)return;o.x=+objX.value;o.y=+objY.value;o.w=+objW.value;o.h=+objH.value;o.r=+objR.value;o.color=objColor.value;o.depth=+objDepth.value;render()}
function rotateSelected(n){if(selected<0)return;objects[selected].r+=n;render()}
function bringFront(){if(selected<0)return;const o=objects.splice(selected,1)[0];objects.push(o);selected=objects.length-1;render()}
function sendBack(){if(selected<0)return;const o=objects.splice(selected,1)[0];objects.unshift(o);selected=0;render()}
function deleteSelected(){if(selected<0)return;objects.splice(selected,1);selected=Math.min(selected,objects.length-1);render()}
function resetScene(){objects=[];selected=-1;addObject('phone');render()}
function loadTemplate(k){const p=presets[k];if(!p)return;objects=[];addObject(p.type,p);if(k==='desk')addObject('shape',{x:100,y:470,w:520,h:35,color:'#8ea386'});if(k==='3d')addObject('shape',{x:170,y:390,w:390,h:30,color:'#d9b66f'});render()}
function duplicateScene(){const copy=objects.map(o=>({...o,id:uid(),x:o.x+20,y:o.y+20}));objects.push(...copy);render()}
function showPanel(name){document.querySelectorAll('.panel-view').forEach(x=>x.classList.add('hidden'));document.getElementById('panel-'+name).classList.remove('hidden')}
function saveMockup(){localStorage.setItem('marijana-mockup-draft',JSON.stringify(objects));alert('Mockup sačuvan kao radna verzija.')}
imgInput.addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{if(selected>=0)objects[selected].src=r.result;else addObject('image',{src:r.result,x:180,y:100,w:300,h:300});render()};r.readAsDataURL(f)});
document.getElementById('scale').addEventListener('input',e=>{if(selected>=0){const o=objects[selected],s=+e.target.value;o.w=(o.baseW||o.w)*s;o.h=(o.baseH||o.h)*s;render()}});
resetScene();