const KEY='marijana_email_sequences_v1';let sequences=JSON.parse(localStorage.getItem(KEY)||'[]');let current=null;
const $=id=>document.getElementById(id);
function blank(){return{id:Date.now(),name:'Nova email sekvenca',type:'welcome',goal:'',audience:'',offer:'',emails:[]}}
function renderList(){const el=$('sequenceList');el.innerHTML='';sequences.forEach(s=>{const d=document.createElement('div');d.className='seq-item'+(current&&current.id===s.id?' active':'');d.textContent=s.name;d.onclick=()=>load(s.id);el.appendChild(d)})}
function load(id){current=sequences.find(x=>x.id===id)||blank();$('sequenceName').value=current.name;$('sequenceType').value=current.type;$('goal').value=current.goal;$('audience').value=current.audience;$('offer').value=current.offer;renderEmails();renderList()}
function sync(){if(!current)return;current.name=$('sequenceName').value||'Nova email sekvenca';current.type=$('sequenceType').value;current.goal=$('goal').value;current.audience=$('audience').value;current.offer=$('offer').value}
function save(){sync();if(!sequences.some(x=>x.id===current.id))sequences.push(current);localStorage.setItem(KEY,JSON.stringify(sequences));renderList();alert('Sekvenca je sačuvana.')}
function renderEmails(){const box=$('emails');box.innerHTML='';$('sequenceMeta').textContent=current.emails.length+' emailova';if(!current.emails.length){box.innerHTML='<div class="empty">Još nema emailova. Dodaj prvi email ili generiši kompletnu sekvencu.</div>';return}current.emails.forEach((e,i)=>{const card=document.createElement('article');card.className='email';card.innerHTML='<div class="email-top"><strong>Email '+(i+1)+'</strong><button class="danger" data-remove="'+i+'">Obriši</button></div><div class="email-grid"><input data-i="'+i+'" data-k="day" value="'+(e.day||'Dan '+(i+1))+'"><input data-i="'+i+'" data-k="subject" placeholder="Naslov emaila" value="'+esc(e.subject||'')+'"><select data-i="'+i+'" data-k="purpose"><option '+(e.purpose==='Vrednost'?'selected':'')+'>Vrednost</option><option '+(e.purpose==='Prodaja'?'selected':'')+'>Prodaja</option><option '+(e.purpose==='Podsetnik'?'selected':'')+'>Podsetnik</option><option '+(e.purpose==='Dobrodošlica'?'selected':'')+'>Dobrodošlica</option></select></div><textarea data-i="'+i+'" data-k="body" placeholder="Sadržaj emaila">'+esc(e.body||'')+'</textarea>';box.appendChild(card)})}
function esc(s){return String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function addEmail(){sync();current.emails.push({day:'Dan '+(current.emails.length+1),subject:'',purpose:'Vrednost',body:''});renderEmails()}
function generate(){sync();const type=current.type;const presets={welcome:[['Dan 0','Dobrodošla — odakle da počnemo?','Dobrodošlica'],['Dan 1','Jedan mali korak koji možeš odmah da uradiš','Vrednost'],['Dan 3','Najčešća greška i kako da je izbegneš','Vrednost'],['Dan 5','Kako izgleda sledeći korak','Vrednost'],['Dan 7','Tvoja sledeća prilika','Prodaja']],lead:[['Dan 0','Evo tvog besplatnog resursa','Dobrodošlica'],['Dan 1','Kako da izvučeš maksimum iz vodiča','Vrednost'],['Dan 3','3 stvari koje najčešće koče rezultat','Vrednost'],['Dan 5','Rešenje koje štedi vreme','Prodaja'],['Dan 7','Da li želiš da nastavimo?','Podsetnik']],sales:[['Dan 0','Problem koji tvoj proizvod rešava','Vrednost'],['Dan 1','Kako izgleda rešenje','Vrednost'],['Dan 2','Šta dobijaš','Prodaja'],['Dan 4','Najčešća pitanja pre kupovine','Prodaja'],['Dan 6','Poslednji poziv','Podsetnik']]}[type]||[['Dan 0','Uvod','Dobrodošlica'],['Dan 2','Korisna ideja','Vrednost'],['Dan 4','Sledeći korak','Prodaja']];current.emails=presets.map(x=>({day:x[0],subject:x[1],purpose:x[2],body:'Ovde će biti generisan sadržaj emaila prilagođen publici, cilju i ponudi projekta.'}));renderEmails();save()}
$('newSequence').onclick=()=>{current=blank();load(current.id)};$('addEmail').onclick=addEmail;$('saveSequence').onclick=save;$('generateSequence').onclick=generate;
$('emails').addEventListener('input',e=>{const i=e.target.dataset.i,k=e.target.dataset.k;if(i!==undefined){current.emails[i][k]=e.target.value;$('sequenceMeta').textContent=current.emails.length+' emailova'}});
$('emails').addEventListener('click',e=>{const i=e.target.dataset.remove;if(i!==undefined){current.emails.splice(Number(i),1);renderEmails()}});
current=sequences[0]||blank();if(!sequences.length)sequences.push(current);load(current.id);
